apiVersion: v1

kind: Service
metadata:
  name: pgadmin
  namespace: playground
  labels:
    app: pgadmin
    group: playground
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: pgadmin
    group: playground
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pgadmin
  namespace: playground
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: pgadmin
        group: playground
    spec:
      containers:
      - name: pgadmin
        image: "{{conf['pgadmin-config']['images'][0]}}"
        ports:
        - containerPort: 80
        env:
        - name: SERVER_HOST
          value: "{{conf['pgadmin-config']['host']}}"
        - name: SERVER_PORT
          value: "{{conf['pgadmin-config']['port']}}"   
        - name: SERVER_NAME
          value: "{{conf['pgadmin-config']['env']}}"                   
        - name: MAINTENANCE_DB_NAME
          value: "{{conf['pgadmin-config']['maintenance-db-name']}}"  
        - name: DB_READ_USERNAME
          value: "{{conf['pgadmin-config']['db-read-username']}}"
        - name: DB_ADMIN_USERNAME
          value: "{{conf['pgadmin-config']['db-admin-username']}}"          
        - name: PGADMIN_PORT
          value: "8080"                      
        - name: PGADMIN_DEFAULT_EMAIL
          valueFrom:
            secretKeyRef:
              name: pgadmin
              key: admin-email
        - name: PGADMIN_DEFAULT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pgadmin
              key: admin-password     
        - name: PGADMIN_READ_EMAIL
          valueFrom:
            secretKeyRef:
              name: pgadmin
              key: read-email
        - name: PGADMIN_READ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pgadmin
              key: read-password                                                                                         
        resources:
          requests:
            memory: "64Mi"
          limits:
            memory: "{{ conf['pgadmin-config']['memory_limits'] or "512Mi"}}"
{% if conf['egov-docker-registry-secret'] %}
      imagePullSecrets:
      - name: regsecret
      - name: allvyregsecret
{% endif %}
