apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: playground
  namespace: playground
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: playground
        group: playground
    spec:
      containers:
      - name: playground
        image: {{conf['playground']['images'][0]}}
