---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: es-alerts
  namespace: monitoring
  labels:
    app: es-alerts
spec:
  replicas: {{conf['es-alerts']['replicas']}}
  template:
    metadata:
      labels:
        app: es-alerts
    spec:
      containers:
      - name: es-alerts
        image: {{conf['es-alerts']['images'][0]}}
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
          requests:
            memory: "64Mi"
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: ES_HOST
          valueFrom:
            configMapKeyRef:
              name: monitoring-config
              key: es-host
        - name: ES_PORT
          valueFrom:
            configMapKeyRef:
              name: monitoring-config
              key: es-port
        - name: LOG_INDEX_NAME
          value: {{conf['es-alerts']['log-index-name']}}
        - name: SLACK_URL
          valueFrom:
            secretKeyRef:
              name: slack
              key: slack-url
