apiVersion: v1
kind: Service
metadata:
  name: tl-calculator
  namespace: egov
  labels:
    app: tl-calculator
    group: rainmaker
  annotations:
    prometheus.io/path: /tl-calculator/prometheus
    prometheus.io/port: "8080"
    prometheus.io/scrape: "true"    
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: tl-calculator
    group: rainmaker
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tl-calculator
  namespace: egov
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  replicas: {{conf['tl-calculator']['replicas']}}
  template:
    metadata:
      labels:
        app: tl-calculator
        group: rainmaker
      annotations:
        pod.beta.kubernetes.io/init-containers: '[
          {
            "name": "tl-calculator-db-migration",
            "image": "{{conf["tl-calculator"]["db_migration_image"]}}",
            "env": [
              {"name": "DB_URL", "valueFrom": {"configMapKeyRef": {"name": "egov-config", "key": "db-url"}}},
              {"name": "SCHEMA_TABLE", "value": "tl_calculator_schema"},
              {"name": "FLYWAY_USER", "valueFrom": {"secretKeyRef": {"name": "db", "key": "flyway-username"}}},
              {"name": "FLYWAY_PASSWORD", "valueFrom": {"secretKeyRef": {"name": "db", "key": "flyway-password"}}},
              {"name": "FLYWAY_LOCATIONS", "valueFrom": {"configMapKeyRef": {"name": "egov-config", "key": "flyway-locations"}}}
            ],
            "imagePullPolicy": "IfNotPresent"
          }
        ]'
    spec:
      containers:
      - name: tl-calculator
        image: {{conf['tl-calculator']['images'][0]}}
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /tl-calculator/health
            port: 8080
          initialDelaySeconds: 90
          timeoutSeconds: 3
          periodSeconds: 30
          successThreshold: 1
          failureThreshold: 5
        livenessProbe:
          httpGet:
            path: /tl-calculator/health
            port: 8080
          initialDelaySeconds: 120
          timeoutSeconds: 3
          periodSeconds: 60
          successThreshold: 1
          failureThreshold: 5
        env:
        - name: SERVER_CONTEXTPATH
          value: /tl-calculator
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            configMapKeyRef:
              name: egov-config
              key: db-url
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: db
              key: username
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db
              key: password
        - name: SERVER_TOMCAT_MAX_THREADS
          value: "{{conf['egov-config']['server-tomcat-max-threads']}}"                
        - name: FLYWAY_ENABLED
          value: "false"
        - name: SPRING_KAFKA_CONSUMER_VALUE_DESERIALIZER
          value: org.egov.tracer.kafka.deserializer.HashMapDeserializer
        - name: SPRING_KAFKA_CONSUMER_KEY_DESERIALIZER
          value: org.apache.kafka.common.serialization.StringDeserializer
        - name: SPRING_KAFKA_CONSUMER_GROUP_ID
          value: tl-calculator
        - name: SPRING_KAFKA_PRODUCER_KEY_SERIALIZER
          value: org.apache.kafka.common.serialization.StringSerializer
        - name: SPRING_KAFKA_PRODUCER_VALUE_SERIALIZER
          value: org.springframework.kafka.support.serializer.JsonSerializer
        - name: KAFKA_TOPICS_SAVE_SERVICE
          value: save-tl-billingslab
        - name: KAFKA_TOPICS_UPDATE_SERVICE
          value: update-tl-billingslab
        - name: EGOV_MDMS_HOST
          value: "{{conf['egov-service-host']['egov-mdms-service']}}"
        - name: EGOV_MDMS_SEARCH_ENDPOINT
          value: /egov-mdms-service/v1/_search
        - name: EGOV_BILLINGSERVICE_HOST
          value: "{{conf['egov-service-host']['billing-service']}}"
        - name: EGOV_TRADELICENSE_HOST
          value: "{{conf['egov-service-host']['tl-services']}}"
        - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
          valueFrom:
            configMapKeyRef:
              name: egov-config
              key: kafka-brokers
        - name: APP_TIMEZONE
          valueFrom:
            configMapKeyRef:
              name: egov-config
              key: timezone
        - name: JAVA_OPTS
          value: "{{conf['tl-calculator']['heap'] or '-Xmx192m -Xms192m'}}"
        - name: JAVA_ARGS
          value: "{{conf['tl-calculator']['java-args']}}"          
        - name: SPRING_JPA_SHOW_SQL
          value: "{{conf['egov-config']['spring-jpa-show-sql']}}"
        - name: SERVER_PORT
          value: "8080"
        - name: JAEGER_SERVICE_NAME
          value: tl-calculator
        - name: JAEGER_SAMPLER_TYPE
          value: remote
        - name: JAEGER_AGENT_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: JAEGER_AGENT_PORT
          value: "6831"
        - name: JAEGER_SAMPLER_MANAGER_HOST_PORT
          value: "$(JAEGER_AGENT_HOST):5778"           
        - name: SECURITY_BASIC_ENABLED
          value: "false"  
        - name: MANAGEMENT_SECURITY_ENABLED
          value: "false"
{% if conf['tl-calculator']['tracing-enabled']%}          
        - name: TRACER_OPENTRACING_ENABLED
          value: "true" 
{% endif %}                       
        # resources:
        #   requests:
        #     memory: "64Mi"
        #   limits:
        #     memory: "{{ conf['tl-calculator']['memory_limits'] or "512Mi"}}"