apiVersion: v1
kind: Service
metadata:
  name: tl-services
  namespace: egov
  labels:
    app: tl-services
    group: rainmaker
  annotations:
    prometheus.io/path: /tl-services/prometheus
    prometheus.io/port: "8080"
    prometheus.io/scrape: "true"    
spec:
  ports:
  - port: 8080
    targetPort: 8080
    name: "spring-boot"  
  - port: 5005
    targetPort: 5005
    name: "jvm-debug"
  selector:
    app: tl-services
    group: rainmaker
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tl-services
  namespace: egov
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  replicas: {{conf['tl-services']['replicas']}}
  template:
    metadata:
      labels:
        app: tl-services
        group: rainmaker
      annotations:
        pod.beta.kubernetes.io/init-containers: '[
          {
            "name": "tl-services-db-migration",
            "image": "{{conf["tl-services"]["db_migration_image"]}}",
            "env": [
              {"name": "DB_URL", "valueFrom": {"configMapKeyRef": {"name": "egov-config", "key": "db-url"}}},
              {"name": "SCHEMA_TABLE", "value": "tl_services_schema"},
              {"name": "FLYWAY_USER", "valueFrom": {"secretKeyRef": {"name": "db", "key": "flyway-username"}}},
              {"name": "FLYWAY_PASSWORD", "valueFrom": {"secretKeyRef": {"name": "db", "key": "flyway-password"}}},
              {"name": "FLYWAY_LOCATIONS", "valueFrom": {"configMapKeyRef": {"name": "egov-config", "key": "flyway-locations"}}}
            ],
            "imagePullPolicy": "IfNotPresent"
          }
        ]'
    spec:
      containers:
      - name: tl-services
        image: {{conf['tl-services']['images'][0]}}
        ports:
        - containerPort: 8080
          name: "spring-boot"
        - containerPort: 5005
          name: "jvm-debug"
        readinessProbe:
          httpGet:
            path: /tl-services/health
            port: 8080
          initialDelaySeconds: 90
          timeoutSeconds: 3
          periodSeconds: 30
          successThreshold: 1
          failureThreshold: 5
        livenessProbe:
          httpGet:
            path: /tl-services/health
            port: 8080
          initialDelaySeconds: 120
          timeoutSeconds: 3
          periodSeconds: 60
          successThreshold: 1
          failureThreshold: 5
        env:
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            configMapKeyRef:
              name: egov-config
              key: db-url
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: db
              key: username
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db
              key: password
        - name: SERVER_TOMCAT_MAX_THREADS
          value: "{{conf['egov-config']['server-tomcat-max-threads']}}"                
        - name: FLYWAY_ENABLED
          value: "false"
        - name: EGOV_IDGEN_HOST
          value: "{{conf['egov-service-host']['egov-idgen']}}"
        - name: EGOV_MDMS_HOST
          value: "{{conf['egov-service-host']['egov-mdms-service']}}"
        - name: EGOV_USER_HOST
          value: "{{conf['egov-service-host']['egov-user']}}"
        - name: EGOV_LOCATION_HOST
          value: "{{conf['egov-service-host']['egov-location']}}"
        - name: EGOV_TL_CALCULATOR_HOST
          value: "{{conf['egov-service-host']['tl-calculator']}}"
        - name: EGOV_PROPERTY_SERVICE_HOST
          value: "{{conf['egov-service-host']['pt-services-v2']}}"
        - name: EGOV_LOCALIZATION_HOST
          value: "{{conf['egov-service-host']['egov-localization']}}"
        - name: EGOV_MDMS_SEARCH_ENDPOINT
          value: "/egov-mdms-service/v1/_search"
        - name: KAFKA_TOPICS_NOTIFICATION_SMS
          value: "egov.core.notification.sms"
        - name: SPRING_KAFKA_CONSUMER_VALUE_DESERIALIZER
          value: org.egov.tracer.kafka.deserializer.HashMapDeserializer
        - name: SPRING_KAFKA_CONSUMER_KEY_DESERIALIZER
          value: org.apache.kafka.common.serialization.StringDeserializer
        - name: SPRING_KAFKA_CONSUMER_GROUP_ID
          value: egov-tl-services
        - name: PERSISTER_SAVE_TRADELICENSE_TOPIC
          value: save-tl-tradelicense
        - name: PERSISTER_UPDATE_TRADELICENSE_TOPIC
          value: update-tl-tradelicense
        - name: PERSISTER_UPDATE_TRADELICENSE_WORKFLOW_TOPIC
          value: update-tl-workflow
        - name: SPRING_KAFKA_PRODUCER_KEY_SERIALIZER
          value: org.apache.kafka.common.serialization.StringSerializer
        - name: SPRING_KAFKA_PRODUCER_VALUE_SERIALIZER
          value: org.springframework.kafka.support.serializer.JsonSerializer
        - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
          valueFrom:
            configMapKeyRef:
              name: egov-config
              key: kafka-brokers
        - name: APP_TIMEZONE
          valueFrom:
            configMapKeyRef:
              name: egov-config
              key: timezone
        - name: JAVA_OPTS
          value: "{{conf['tl-services']['heap'] or '-Xmx192m -Xms192m'}}"
        - name: JAVA_ARGS
          value: "{{conf['tl-services']['java-args']}}"
        - name: JAVA_ENABLE_DEBUG
          value: "{{conf['tl-services']['java-debug']}}"           
        - name: SPRING_JPA_SHOW_SQL
          value: "{{conf['egov-config']['spring-jpa-show-sql']}}"
        - name: SERVER_PORT
          value: "8080"
        - name: EGOV_IDGEN_TL_APPLICATIONNUM_FORMAT
          value: "PB-TL-[cy:yyyy-MM-dd]-[SEQ_EG_TL_APL]"
        - name: EGOV_IDGEN_TL_LICENSENUMBER_FORMAT
          value: "PB-TL-[cy:yyyy-MM-dd]-[SEQ_EG_PT_LN]"
        - name: JAEGER_SERVICE_NAME
          value: tl-services
        - name: JAEGER_SAMPLER_TYPE
          value: remote
        - name: JAEGER_AGENT_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: JAEGER_AGENT_PORT
          value: "6831"
        - name: JAEGER_SAMPLER_MANAGER_HOST_PORT
          value: "$(JAEGER_AGENT_HOST):5778"        
        - name: SECURITY_BASIC_ENABLED
          value: "false"  
        - name: MANAGEMENT_SECURITY_ENABLED
          value: "false"     
{% if conf['tl-services']['tracing-enabled']%}          
        - name: TRACER_OPENTRACING_ENABLED
          value: "true" 
{% endif %}                         
{% if conf['egov-config']['tracer-errors-provideexceptionindetails'] %}
        - name: TRACER_ERRORS_PROVIDEEXCEPTIONINDETAILS
          value: "{{conf['egov-config']['tracer-errors-provideexceptionindetails']}}"
{% endif %}
        # resources:
        #   requests:
        #     memory: "64Mi"
        #   limits:
        #     memory: "{{ conf['tl-services']['memory_limits'] or "512Mi"}}"
