apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: backbone
  labels:
    app: kafka
spec:
  ports:
  - name: kafka
    port: 9092
    protocol: TCP
    targetPort: 9092
  - name: kafka-jmx
    port: 7071
    protocol: TCP
    targetPort: 7071
  clusterIP: None
  selector:
    app: kafka
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: kafka
  namespace: backbone
spec:
  replicas: {{conf['kafka']['replicas']}}
  serviceName: "kafka"
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka
        image: {{conf['kafka']['images'][0]}}
        env:
        - name: KAFKA_HEAP_OPTS
          value: "-Xmx256M -Xms128M"
        - name: KAFKA_ADVERTISED_PORT
          value: "9092"
        - name: KAFKA_PORT
          value: "9092"
        - name: KAFKA_ZOOKEEPER_CONNECT
          valueFrom:
            configMapKeyRef:
              name: kafka-config
              key: zookeeper-connect
        - name: KAFKA_REQUEST_TIMEOUT_MS
          value: "100000"
{% if conf['kafka']['jmx-enabled'] %}
        - name: JMX_ENABLED
          value: "true"
{% endif %}
        volumeMounts:
        - name: kafka-data
          mountPath: /kafka
        ports:
        - containerPort: 9092
          name: kafka
        - containerPort: 7071
          name: jmx
  volumeClaimTemplates:
  - metadata:
      name: kafka-data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi
