apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: backbone
  labels:
    app: redis
spec:
  ports:
  - port: 6379
    targetPort: 6379
    protocol: TCP
  selector:
    app: redis
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis
  namespace: backbone
spec:
  replicas: {{conf['redis']['replicas']}}
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: {{conf['redis']['images'][0]}}
        command:
        - "redis-server"
        ports:
        - containerPort: 6379