apiVersion: v1
kind: Service
metadata:
  name: egov-notification-sms
  namespace: egov
  labels:
    app: egov-notification-sms
    group: core
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: egov-notification-sms
    group: core
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: egov-notification-sms
  namespace: egov
spec:
  replicas: {{conf['egov-notification-sms']['replicas']}}
  template:
    metadata:
      labels:
        app: egov-notification-sms
        group: core
    spec:
      containers:
      - name: egov-notification-sms
        image: {{conf['egov-notification-sms']['images'][0]}}
        env:
        - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
          valueFrom:
            configMapKeyRef:
              name: egov-config
              key: kafka-brokers
        - name: KAFKA_TOPICS_NOTIFICATION_SMS_NAME
          value: egov.core.notification.sms
        - name: KAFKA_TOPICS_NOTIFICATION_SMS_ID
          value: egov.core.notification.sms
        - name: KAFKA_TOPICS_NOTIFICATION_SMS_GROUP
          value: egov.core.notification.sms
        - name: SMS_PROVIDER_URL
          value: "{{conf['egov-notification-sms']['sms-provider-url']}}"
        - name: SMS_SENDER_USERNAME
          valueFrom:
            secretKeyRef:
              name: egov-notification-sms
              key: username
        - name: SMS_SENDER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: egov-notification-sms
              key: password
        - name: SMS_ENABLED
          valueFrom:
            configMapKeyRef:
              name: egov-config
              key: sms-enabled
        - name: SMS_SENDER
          value: "{{conf['egov-notification-sms']['sms-sender']}}"
        - name: SMS_SENDER_REQUESTTYPE
          value: "{{conf['egov-notification-sms']['sms-sender-requesttype']}}"
{% if conf['egov-notification-sms']['sms-custom-config'] %}
        - name: SMS_SENDER_REQ_PARAM_NAME
          value: "senderid"
        - name: SMS_SENDER_USERNAME_REQ_PARAM_NAME
          value: "username"
        - name: SMS_SENDER_PASSWORD_REQ_PARAM_NAME
          value: "password"
        - name: SMS_DESTINATION_MOBILE_REQ_PARAM_NAME
          value: "mobileno"
        - name: SMS_MESSAGE_REQ_PARAM_NAME
          value: "content"
        - name: "SMS_EXTRA_REQ_PARAMS"
          value: "messageType=text"
        - name: SMS_VERIFY_RESPONSE
          value: "true"
        - name: SMS_VERIFY_RESPONSECONTAINS
          value: "Message submitted successfully"
        - name: SMS_VERIFY_SSL
          value: "false"
        - name: SMS_URL_DONT_ENCODE_URL
          value: "true"
{% endif %}
        - name: FLYWAY_ENABLED
          value: "false"
        - name: JAVA_OPTS
          value: "{{conf['egov-notification-sms']['heap'] or '-Xmx192m -Xms192m'}}"
        - name: APP_TIMEZONE
          valueFrom:
            configMapKeyRef:
              name: egov-config
              key: timezone
        resources:
          requests:
            memory: "64Mi"
          limits:
            memory: "{{ conf['egov-notification-sms']['memory_limits'] or "512Mi"}}"
