apiVersion: v1
kind: Service
metadata:
  name: egov-workflow
  namespace: egov
  labels:
    app: egov-workflow
    group: core
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: egov-workflow
    group: core
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: egov-workflow
  namespace: egov
spec:
  replicas: {{conf['egov-workflow']['replicas']}}
  template:
    metadata:
      labels:
        app: egov-workflow
        group: core
      annotations:
        pod.beta.kubernetes.io/init-containers: '[
          {
            "name": "egov-workflow-db-migration",
            "image": "{{conf["egov-workflow"]["db_migration_image"]}}",
            "env": [
              {"name": "DB_URL", "valueFrom": {"configMapKeyRef": {"name": "egov-config", "key": "db-url"}}},
              {"name": "SCHEMA_TABLE", "value": "egov_workflow_schema"},
              {"name": "FLYWAY_USER", "valueFrom": {"secretKeyRef": {"name": "db", "key": "flyway-username"}}},
              {"name": "FLYWAY_PASSWORD", "valueFrom": {"secretKeyRef": {"name": "db", "key": "flyway-password"}}},
              {"name": "FLYWAY_LOCATIONS", "valueFrom": {"configMapKeyRef": {"name": "egov-config", "key": "flyway-locations"}}}
            ],
            "imagePullPolicy": "IfNotPresent"
          }
        ]'
    spec:
      containers:
      - name: egov-workflow
        image: {{conf['egov-workflow']['images'][0]}}
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            configMapKeyRef:
              name: egov-config
              key: db-url
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: db
              key: username
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db
              key: password
        - name: SPRING_DATASOURCE_TOMCAT_INITIAL_SIZE
          valueFrom:
            configMapKeyRef:
              name: egov-config
              key: spring-datasource-tomcat-initialSize
        - name: EGOV_SERVICES_BOUNDARY_HOST
          value: "{{conf['egov-service-host']['egov-location']}}"
        - name: EGOV_SERVICES_PGRREST_HOST
          value: "{{conf['egov-service-host']['pgr-rest']}}"
        - name: EGOV_SERVICES_HRMASTERS_HOST
          value: "{{conf['egov-service-host']['hr-masters']}}"
        - name: EGOV_SERVICES_HREMPLOYEE_HOST
          value: "{{conf['egov-service-host']['hr-employee']}}"
        - name: EGOV_SERVICES_COMMONMASTERS_HOST
          value: "{{conf['egov-service-host']['egov-common-masters']}}"
        - name: SERVER_PORT
          value: "8080"
        - name: FLYWAY_ENABLED
          value: "false"
        - name: USER_SERVICE_URL
          value: "{{conf['egov-service-host']['egov-user-egov']}}"
        - name: EGOV_SERVICES_PGRMASTER_HOST
          value: "{{conf['egov-service-host']['pgr-master']}}"
        - name: APP_TIMEZONE
          valueFrom:
            configMapKeyRef:
              name: egov-config
              key: timezone
        - name: SPRING_JPA_SHOW_SQL
          value: "{{conf['egov-config']['spring-jpa-show-sql']}}"
        - name: JAVA_OPTS
          value: "{{conf['egov-workflow']['heap'] or '-Xmx192m -Xms192m'}}"
        - name: KAFKA_CONFIG_BOOTSTRAP_SERVER_CONFIG
          valueFrom:
            configMapKeyRef:
              name: egov-config
              key: kafka-brokers
        resources:
          requests:
            memory: "64Mi"
          limits:
            memory: "{{ conf['egov-workflow']['memory_limits'] or "512Mi"}}"
