apiVersion: v1
kind: Service
metadata:
  name: egov-persister
  namespace: egov
  labels:
    app: egov-persister
    group: core
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: egov-persister
    group: core
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: egov-persister
  namespace: egov
spec:
  replicas: {{conf['egov-persister']['replicas']}}
  template:
    metadata:
      labels:
        app: egov-persister
        group: core
    spec:
      containers:
      - name: egov-persister
        image: {{conf['egov-persister']['images'][0]}}
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            configMapKeyRef:
              name: egov-config
              key: db-url
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: db
              key: username
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db
              key: password
        - name: FLYWAY_ENABLED
          value: "false"
        - name: EGOV_PERSIST_YML_REPO_PATH
          value: "{{conf['egov-persister']['persist-yml-path'] }}"
        - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
          valueFrom:
            configMapKeyRef:
              name: egov-config
              key: kafka-brokers
        - name: APP_TIMEZONE
          valueFrom:
            configMapKeyRef:
              name: egov-config
              key: timezone
        - name: JAVA_OPTS
          value: "{{conf['egov-persister']['heap'] or '-Xmx192m -Xms192m'}}"
        - name: SERVER_PORT
          value: "8080"
        - name: JAEGER_SERVICE_NAME
          value: egov-persister
        - name: JAEGER_SAMPLER_TYPE
          value: const
        - name: JAEGER_SAMPLER_PARAM
          value: "1"
        - name: JAEGER_AGENT_HOST
          value: jaeger-agent.monitoring
        - name: JAEGER_AGENT_PORT
          value: "6831"
        resources:
          requests:
            memory: "64Mi"
          limits:
            memory: "{{ conf['egov-persister']['memory_limits'] or "512Mi"}}"
