apiVersion: v1
kind: Service
metadata:
  name: egov-searcher
  namespace: egov
  labels:
    app: egov-searcher
    group: core
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: egov-searcher
    group: core
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: egov-searcher
  namespace: egov
spec:
  replicas: {{conf['egov-searcher']['replicas']}}
  template:
    metadata:
      labels:
        app: egov-searcher
        group: core
    spec:
      containers:
      - name: egov-searcher
        image: {{conf['egov-searcher']['images'][0]}}
        ports:
        - containerPort: 8080
        env:
        - name: FLYWAY_ENABLED
          value: "false"
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            configMapKeyRef:
              name: egov-config
              key: db-url
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: db
              key: username
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db
              key: password
        - name: SEARCH_YAML_PATH
          value: "{{conf['egov-searcher']['search-yaml-path']}}"
        - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
          valueFrom:
            configMapKeyRef:
              name: egov-config
              key: kafka-brokers
        - name: APP_TIMEZONE
          valueFrom:
            configMapKeyRef:
              name: egov-config
              key: timezone
        - name: JAVA_OPTS
          value: "{{conf['egov-searcher']['heap'] or '-Xmx192m -Xms192m'}}"
        - name: SERVER_PORT
          value: "8080"
        resources:
          requests:
            memory: "64Mi"
          limits:
            memory: "{{conf['egov-searcher']['memory_limits'] or "512Mi"}}"