apiVersion: v1
kind: Service
metadata:
  name: egov-indexer
  namespace: egov
  labels:
    app: egov-indexer
    group: core
  annotations:
    prometheus.io/path: /egov-indexer/prometheus
    prometheus.io/port: "8080"
    prometheus.io/scrape: "true"      
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: egov-indexer
    group: core
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: egov-indexer
  namespace: egov
spec:
  replicas: {{conf['egov-indexer']['replicas']}}
  template:
    metadata:
      labels:
        app: egov-indexer
        group: core
      annotations:
        pod.beta.kubernetes.io/init-containers: '[
          {
            "name": "egov-indexer-db-migration",
            "image": "{{conf["egov-indexer"]["db_migration_image"]}}",
            "env": [
              {"name": "DB_URL", "valueFrom": {"configMapKeyRef": {"name": "egov-config", "key": "db-url"}}},
              {"name": "SCHEMA_TABLE", "value": "egov_indexer_schema"},
              {"name": "FLYWAY_USER", "valueFrom": {"secretKeyRef": {"name": "db", "key": "flyway-username"}}},
              {"name": "FLYWAY_PASSWORD", "valueFrom": {"secretKeyRef": {"name": "db", "key": "flyway-password"}}},
              {"name": "FLYWAY_LOCATIONS", "valueFrom": {"configMapKeyRef": {"name": "egov-config", "key": "flyway-locations"}}}
            ],
            "imagePullPolicy": "IfNotPresent"
          }
        ]'
    spec:
      containers:
      - name: egov-indexer
        image: {{conf['egov-indexer']['images'][0]}}
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            configMapKeyRef:
              name: egov-config
              key: db-url
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: db
              key: username
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db
              key: password
        - name: APP_TIMEZONE
          valueFrom:
            configMapKeyRef:
              name: egov-config
              key: timezone
        - name: EGOV_SERVICES_INFRA_INDEXER_HOST
          value: "{{conf['egov-service-host']['egov-indexer']}}"
        - name: EGOV_INFRA_INDEXER_HOST
          valueFrom:
            configMapKeyRef:
              name: egov-config
              key: es-indexer-host
        - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
          valueFrom:
            configMapKeyRef:
              name: egov-config
              key: kafka-brokers
        - name: SERVER_TOMCAT_MAX_THREADS
          value: "{{conf['egov-config']['server-tomcat-max-threads']}}"                
        - name: EGOV_INDEXER_YML_REPO_PATH
#          value: "https://raw.githubusercontent.com/egovernments/egov-services/master/citizen/citizen-indexer/src/main/resources/watercharges-indexer.yml,https://raw.githubusercontent.com/egovernments/egov-services/master/citizen/citizen-indexer/src/main/resources/property-tax.yml,https://raw.githubusercontent.com/egovernments/egov-services/master/citizen/citizen-indexer/src/main/resources/swm-service-indexer.yml,https://raw.githubusercontent.com/egovernments/egov-services/master/citizen/citizen-indexer/src/main/resources/asset-service-maha.yml,https://raw.githubusercontent.com/egovernments/egov-services/master/core/egov-indexer/s,https://raw.githubusercontent.com/egovernments/egov-services/master/core/egov-indexer/src/main/resources/lcms-indexer.yml,https://raw.githubusercontent.com/egovernments/egov-services/master/core/egov-indexer/src/main/resources/inventory-service-indexer.yml"
          value: "{{conf['egov-config']['egov-indexer-yaml-repo-path']}}"
{% if conf['egov-config']['serializers-timezone-in-ist'] %}
        - name: SPRING_KAFKA_CONSUMER_VALUE_DESERIALIZER
          value: org.egov.tracer.kafka.deserializer.ISTTimeZoneHashMapDeserializer
        - name: SPRING_KAFKA_PRODUCER_VALUE_SERIALIZER
          value: org.egov.tracer.kafka.serializer.ISTTimeZoneJsonSerializer
{% endif %}
        - name: JAVA_OPTS
          value: "{{conf['egov-indexer']['heap'] or '-Xmx192m -Xms192m'}}"
        - name: SERVER_PORT
          value: "8080"
        - name: FLYWAY_ENABLED
          value: "false"
        - name: SECURITY_BASIC_ENABLED
          value: "false"  
        - name: MANAGEMENT_SECURITY_ENABLED
          value: "false"           
        resources:
          requests:
            memory: "128Mi"
          limits:
            memory: "{{ conf['egov-indexer']['memory_limits'] or "512Mi"}}"
