apiVersion: v1
kind: Service
metadata:
  name: egov-mdms-service-test
  namespace: egov
  labels:
    app: egov-mdms-service-test
    group: core
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: egov-mdms-service-test
    group: core
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: egov-mdms-service-test
  namespace: egov
spec:
  replicas: {{conf['egov-mdms-service-test']['replicas']}}
  template:
    metadata:
      labels:
        app: egov-mdms-service-test
        group: core
    spec:
      containers:
      - name: egov-mdms-service-test
        image: {{conf['egov-mdms-service-test']['images'][0]}}
        ports:
        - containerPort: 8080
        env:
        - name: APP_TIMEZONE
          valueFrom:
            configMapKeyRef:
              name: egov-config
              key: timezone
        - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
          valueFrom:
            configMapKeyRef:
              name: egov-config
              key: kafka-brokers
        - name: SERVER_CONTEXT_PATH
          value: /egov-mdms-service-test
        - name: SPRING_KAFKA_CONSUMER_KEY_DESERIALIZER
          value: org.apache.kafka.common.serialization.StringDeserializer
        - name: SPRING_KAFKA_CONSUMER_GROUP_ID
          value: mdms-service-test
        - name: SPRING_KAFKA_PRODUCER_KEY_SERIALIZER
          value: org.apache.kafka.common.serialization.StringSerializer
{% if conf['egov-config']['serializers-timezone-in-ist'] %}
        - name: SPRING_KAFKA_CONSUMER_VALUE_DESERIALIZER
          value: org.egov.tracer.kafka.deserializer.ISTTimeZoneHashMapDeserializer
        - name: SPRING_KAFKA_PRODUCER_VALUE_SERIALIZER
          value: org.egov.tracer.kafka.serializer.ISTTimeZoneJsonSerializer
{% endif %}
        - name: JAVA_OPTS
          value: "{{conf['egov-mdms-service-test']['heap'] or '-Xmx64m -Xms64m'}}"
        - name: SERVER_PORT
          value: "8080"
        - name: EGOV_MDMS_CONF_PATH
          value: "/opt/mdms/data"
        resources:
          requests:
            memory: "64Mi"
          limits:
            memory: "{{conf['egov-mdms-service-test']['memory_limits'] or "256Mi"}}"
