apiVersion: v1
kind: Service
metadata:
  name: egov-localization
  namespace: egov
  labels:
    app: egov-localization
    group: core
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: egov-localization
    group: core
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: egov-localization
  namespace: egov
spec:
  # strategy:
  #   type: RollingUpdate
  #   rollingUpdate:
  #     maxUnavailable: 0
  #     maxSurge: 1
  replicas: {{conf['egov-localization']['replicas']}}
  template:
    metadata:
      labels:
        app: egov-localization
        group: core
      annotations:
        pod.beta.kubernetes.io/init-containers: '[
        {% if conf["egov-localization"]["env_specific_db_migration_image"] %}
          {
            "name": "egov-localization-env-specific-db-migration",
            "image": "{{conf["egov-localization"]["env_specific_db_migration_image"]}}",
            "command": ["sh", "-c", "cp -R /egov/db/migration/core/egov-localization/* /env_specific_db_migration/"],
            "volumeMounts": [
              {
                "mountPath": "/env_specific_db_migration",
                "name": "env-specific-db-migration"
              }
            ],
            "imagePullPolicy": "Always"
          },
        {% endif %}
          {
            "name": "egov-localization-db-migration",
            "image": "{{conf["egov-localization"]["db_migration_image"]}}",
            "env": [
              {"name": "DB_URL", "valueFrom": {"configMapKeyRef": {"name": "egov-config", "key": "db-url"}}},
              {"name": "SCHEMA_TABLE", "value": "egov_localization_schema"},
              {"name": "FLYWAY_USER", "valueFrom": {"secretKeyRef": {"name": "db", "key": "flyway-username"}}},
              {"name": "FLYWAY_PASSWORD", "valueFrom": {"secretKeyRef": {"name": "db", "key": "flyway-password"}}},
              {"name": "FLYWAY_LOCATIONS", "valueFrom": {"configMapKeyRef": {"name": "egov-config", "key": "flyway-locations"}}}
            ],
            "volumeMounts": [
              {
                "mountPath": "/env_specific_db_migration",
                "name": "env-specific-db-migration"
              }
            ],
            "imagePullPolicy": "IfNotPresent"
          }
        ]'
    spec:
      containers:
      - name: egov-localization
        image: {{conf['egov-localization']['images'][0]}}
        ports:
        - containerPort: 8080
        # readinessProbe:
        #   httpGet:
        #     path: /localization/health
        #     port: 8080
        #   initialDelaySeconds: 90
        #   timeoutSeconds: 3
        #   periodSeconds: 30
        #   successThreshold: 1
        #   failureThreshold: 5
        # livenessProbe:
        #   httpGet:
        #     path: /localization/health
        #     port: 8080
        #   initialDelaySeconds: 120
        #   timeoutSeconds: 3
        #   periodSeconds: 60
        #   successThreshold: 1
        #   failureThreshold: 5
        env:
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            configMapKeyRef:
              name: egov-config
              key: db-url
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: db
              key: username
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db
              key: password
        - name: SPRING_DATASOURCE_TOMCAT_INITIAL_SIZE
          valueFrom:
            configMapKeyRef:
              name: egov-config
              key: spring-datasource-tomcat-initialSize
        - name: SERVER_PORT
          value: "8080"
        - name: FLYWAY_ENABLED
          value: "false"
        - name: JAVA_OPTS
          value: "{{conf['egov-localization']['heap'] or '-Xmx64m -Xms64m'}}"
        - name: SPRING_REDIS_HOST
          value: redis.backbone
        - name: SPRING_REDIS_PORT
          value: "6379"
        - name: APP_TIMEZONE
          valueFrom:
            configMapKeyRef:
              name: egov-config
              key: timezone
        - name: SPRING_JPA_SHOW_SQL
          value: "{{conf['egov-config']['spring-jpa-show-sql']}}"
        - name: JAEGER_SERVICE_NAME
          value: egov-localization
        - name: JAEGER_SAMPLER_TYPE
          value: const
        - name: JAEGER_SAMPLER_PARAM
          value: "1"
        - name: JAEGER_AGENT_HOST
          value: jaeger-agent.monitoring
        - name: JAEGER_AGENT_PORT
          value: "6831"
        resources:
          requests:
            memory: "64Mi"
          limits:
            memory: "{{ conf['egov-localization']['memory_limits'] or "256Mi"}}"
      volumes:
      - name: env-specific-db-migration
        emptyDir: {}
{% if conf['egov-docker-registry-secret'] %}
      imagePullSecrets:
      - name: regsecret
      - name: allvyregsecret
{% endif %}
