apiVersion: v1
kind: Service
metadata:
  name: telemetry
  namespace: egov
  labels:
    app: telemetry
    group: core
spec:
  ports:
  - port: 9001
    targetPort: 9001
  selector:
    app: telemetry
    group: core
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: telemetry
  namespace: egov
spec:
  replicas: {{conf['telemetry']['replicas']}}
  template:
    metadata:
      labels:
        app: telemetry
        group: core
    spec:
      containers:
      - name: telemetry
        image: {{conf['telemetry']['images'][0]}}
        ports:
        - containerPort: 9001
        env:
        - name: APP_TIMEZONE
          valueFrom:
            configMapKeyRef:
              name: egov-config
              key: timezone
        - name: telemetry_kafka_broker_list
          valueFrom:
            configMapKeyRef:
              name: egov-config
              key: kafka-brokers
        - name: telemetry_kafka_topic
          value: "telemetry-raw-input"
        - name: telemetry_local_storage_type
          value: "kafka"
        - name: telemetry_service_port
          value: "9001"
        - name: telemetry_file_maxsize
          value: "100m"
        - name: telemetry_file_maxfiles
          value: "100"
        - name: telemetry_service_threads
          value: "2"
        - name: SERVER_PORT
          value: "9001"
        resources:
          requests:
            memory: "256Mi"
          limits:
            memory: "{{ conf['telemetry']['memory_limits'] or "1Gi"}}"
