apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: lams-workflow
  namespace: egov
spec:
  replicas: {{conf['lams-workflow']['replicas']}}
  template:
    metadata:
      labels:
        app: lams-workflow
        group: lams
    spec:
      containers:
      - name: lams-workflow
        image: {{conf['lams-workflow']['images'][0]}}
        ports:
        - containerPort: 8080
        env:
        - name: EGOV_SERVICES_WORKFLOW_SERVICE_HOSTNAME
          value: "{{conf['egov-service-host']['egov-common-workflows']}}"
        - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
          valueFrom:
            configMapKeyRef:
              name: egov-config
              key: kafka-brokers
        - name: SERVER_PORT
          value: "8080"
        - name: KAFKA_TOPICS_SAVE_AGREEMENT
          value: agreement-save-db
        - name: KAFKA_TOPICS_UPDATE_AGREEMENT
          value: agreement-update-db
        - name: KAFKA_TOPICS_START_WORKFLOW
          value: lams-workflow-start
        - name: KAFKA_TOPICS_UPDATE_WORKFLOW
          value: lams-workflow-update
        - name: APP_TIMEZONE
          valueFrom:
            configMapKeyRef:
              name: egov-config
              key: timezone
        - name: SPRING_JPA_SHOW_SQL
          value: "{{conf['egov-config']['spring-jpa-show-sql']}}"
{% if conf['lams-workflow']['memory_limits'] %}
        resources:
          requests:
            memory: "64Mi"
          limits:
            memory: "{{ conf['lams-workflow']['memory_limits'] or "256Mi"}}"
{% endif %}
