apiVersion: v1
kind: Service
metadata:
  name: report
  namespace: egov
  labels:
    app: report
    group: reportinfra
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: report
    group: reportinfra
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: report
  namespace: egov
spec:
  replicas: {{conf['report']['replicas']}}
  template:
    metadata:
      labels:
        app: report
        group: reportinfra
    spec:
      containers:
      - name: report
        image: {{conf['report']['images'][0]}}
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            configMapKeyRef:
              name: egov-config
              key: db-url
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: db
              key: username
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db
              key: password
        - name: SERVER_CONTEXTPATH
          value: /report
        - name: FLYWAY_ENABLED
          value: "false"
{% if conf['report']['report-locationsfile-path'] %}
        - name: REPORT_LOCATIONSFILE_PATH
          value: "{{conf['report']['report-locationsfile-path']}}"
{% endif %}
        - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
          valueFrom:
            configMapKeyRef:
              name: egov-config
              key: kafka-brokers
        - name: APP_TIMEZONE
          valueFrom:
            configMapKeyRef:
              name: egov-config
              key: timezone
        - name: JAVA_OPTS
          value: "{{conf['report']['heap'] or '-Xmx192m -Xms192m'}}"
        - name: SPRING_JPA_SHOW_SQL
          value: "{{conf['egov-config']['spring-jpa-show-sql']}}"
        - name: SERVER_PORT
          value: "8080"
        - name: TRACER_OPENTRACING_ENABLED
          value: "{{conf['report']['tracing-enabled']}}"
        - name: JAEGER_SERVICE_NAME
          value: report-service          
        - name: JAEGER_SAMPLER_TYPE
          value: remote
        - name: JAEGER_AGENT_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: JAEGER_AGENT_PORT
          value: "6831"
        - name: JAEGER_SAMPLER_MANAGER_HOST_PORT
          value: "$(JAEGER_AGENT_HOST):5778"              
        - name: SECURITY_BASIC_ENABLED
          value: "false"  
        - name: MANAGEMENT_SECURITY_ENABLED
          value: "false"                    
        resources:
          requests:
            memory: "64Mi"
          limits:
            memory: "{{ conf['report']['memory_limits'] or "512Mi"}}"
