apiVersion: v1
kind: Service
metadata:
  name: data-sync-employee
  namespace: egov
  labels:
    app: data-sync-employee
    group: hybrid-data-sync
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: data-sync-employee
    group: hybrid-data-sync
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: data-sync-employee
  namespace: egov
spec:
  replicas: {{conf['data-sync-employee']['replicas']}}
  template:
    metadata:
      labels:
        app: data-sync-employee
        group: hybrid-data-sync
    spec:
      containers:
      - name: data-sync-employee
        image: {{conf['data-sync-employee']['images'][0]}}
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            configMapKeyRef:
              name: egov-config
              key: db-url
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: db
              key: username
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db
              key: password
        - name: SPRING_DATASOURCE_TOMCAT_INITIAL_SIZE
          valueFrom:
            configMapKeyRef:
              name: egov-config
              key: spring-datasource-tomcat-initialSize
        - name: SERVER_PORT
          value: "8080"
        - name: FLYWAY_ENABLED
          value: "false"
        - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
          valueFrom:
            configMapKeyRef:
              name: egov-config
              key: kafka-brokers
        - name: SERVER_CONTEXTPATH
          value: /data-sync-employee
        - name: EGOV_SERVICES_FILESTORE_HOSTNAME
          value: "{{conf['egov-service-host']['egov-filestore']}}"
        - name: SPRING_KAFKA_CONSUMER_KEY_DESERIALIZER
          value: org.apache.kafka.common.serialization.StringDeserializer
        - name: SPRING_KAFKA_CONSUMER_GROUP_ID
          value: datasyncemployee-group
        - name: SPRING_KAFKA_PRODUCER_KEY_SERIALIZER
          value: org.apache.kafka.common.serialization.StringSerializer
        - name: KAFKA_TOPICS_EMPLOYEE_SYNC_NAME
          value: egov.datasync
{% if conf['egov-config']['serializers-timezone-in-ist'] %}
        - name: SPRING_KAFKA_CONSUMER_VALUE_DESERIALIZER
          value: org.egov.tracer.kafka.deserializer.ISTTimeZoneHashMapDeserializer
        - name: SPRING_KAFKA_PRODUCER_VALUE_SERIALIZER
          value: org.egov.tracer.kafka.serializer.ISTTimeZoneJsonSerializer
{% endif %}
        - name: KAFKA_TOPICS_EMPLOYEE_SYNC_ID
          value: datasync
        - name: JAVA_OPTS
          value: "{{conf['data-sync-employee']['heap'] or '-Xmx64m -Xms64m'}}"
        - name: APP_TIMEZONE
          valueFrom:
            configMapKeyRef:
              name: egov-config
              key: timezone
        - name: SPRING_JPA_SHOW_SQL
          value: "{{conf['egov-config']['spring-jpa-show-sql']}}"
      volumes:
      - name: env-specific-db-migration
        emptyDir: {}
      imagePullSecrets:
      - name: regsecret
