{% for index in range(conf['data-sync-task']['profiles'] | length) %}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: data-sync-task-{{conf['data-sync-task']['profiles'][index]}}
  namespace: egov
spec:
  replicas: {{conf['data-sync-task']['replicas']}}
  template:
    metadata:
      labels:
        app: data-sync-task-{{conf['data-sync-task']['profiles'][index]}}
        group: hybrid-data-sync
      annotations:
        pod.beta.kubernetes.io/init-containers: '[
          {
            "name": "data-sync-task-db-migration",
            "image": "{{conf["data-sync-task"]["db_migration_image"]}}",
            "env": [
              {"name": "DB_URL", "valueFrom": {"configMapKeyRef": {"name": "egov-config", "key": "db-url"}}},
              {"name": "SCHEMA_TABLE", "value": "data_sync_task_schema"},
              {"name": "FLYWAY_USER", "valueFrom": {"secretKeyRef": {"name": "db", "key": "flyway-username"}}},
              {"name": "FLYWAY_PASSWORD", "valueFrom": {"secretKeyRef": {"name": "db", "key": "flyway-password"}}},
              {"name": "FLYWAY_LOCATIONS", "valueFrom": {"configMapKeyRef": {"name": "egov-config", "key": "flyway-locations"}}}
            ],
            "imagePullPolicy": "IfNotPresent"
          }
        ]'
    spec:
      containers:
      - name: data-sync-task-{{conf['data-sync-task']['profiles'][index]}}
        image: {{conf['data-sync-task']['images'][0]}}
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            configMapKeyRef:
              name: egov-config
              key: db-url
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: db
              key: username
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db
              key: password
        - name: SPRING_DATASOURCE_TOMCAT_INITIAL_SIZE
          valueFrom:
            configMapKeyRef:
              name: egov-config
              key: spring-datasource-tomcat-initialSize
        - name: SERVER_PORT
          value: "8080"
        - name: SPRING_PROFILES_ACTIVE
          value: "{{conf['data-sync-task']['profiles'][index]}}"
        - name: FLYWAY_ENABLED
          value: "false"
        - name: RATE_IN_MILLISECONDS
          value: "{{ conf['data-sync-task']['rate_in_milliseconds'] }}"
        - name: APP_TIMEZONE
          valueFrom:
            configMapKeyRef:
              name: egov-config
              key: timezone
        - name: SOURCE_SCHEMAS
          value: "{{ conf['data-sync-task']['source_schemas'] }}"
        - name: SPRING_JPA_SHOW_SQL
          value: "{{conf['egov-config']['spring-jpa-show-sql']}}"
---
{% endfor %}
