apiVersion: v1
kind: Service
metadata:
  name: egf-voucher-workflow
  namespace: egov
  labels:
    app: egf-voucher-workflow
    group: financials
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: egf-voucher-workflow
    group: financials
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: egf-voucher-workflow
  namespace: egov
spec:
  replicas: {{conf['egf-voucher-workflow']['replicas']}}
  template:
    metadata:
      labels:
        app: egf-voucher-workflow
        group: financials
    spec:
      containers:
      - name: egf-voucher-workflow
        image: {{conf['egf-voucher-workflow']['images'][0]}}
        ports:
        - containerPort: 8080
        env:
        - name: SERVER_CONTEXT_PATH
          value: /egf-voucher-workflow
        - name: SPRING_KAFKA_CONSUMER_KEY_DESERIALIZER
          value: org.apache.kafka.common.serialization.StringDeserializer
        - name: SPRING_KAFKA_CONSUMER_GROUP_ID
          value: tl-workflow
        - name: SPRING_KAFKA_PRODUCER_KEY_SERIALIZER
          value: org.apache.kafka.common.serialization.StringSerializer
        - name: EGOV_SERVICES_EGF_VOUCHER_VALIDATED_TOPIC
          value: egov.egf.voucher.validated
        - name: EGOV_SERVICES_EGF_VOUCHER_VALIDATED_GROUP
          value: egov.egf.voucher.validated.group
        - name: EGOV_SERVICES_EGF_VOUCHER_VALIDATED_ID
          value: egov.egf.voucher.validated.id
        - name: EGOV_SERVICES_EGF_VOUCHER_WORKFLOW_POPULATED_TOPIC
          value: egov.egf.voucher.workflow.populated
        - name: EGOV_SERVICES_EGF_VOUCHER_WORKFLOW_POPULATED_KEY
          value: egov.egf.voucher.workflow.populated.key
        - name: EGOV_SERVICES_COMMON_WORKFLOW_HOSTNAME
          value: "{{conf['egov-service-host']['egov-common-workflows']}}"
{% if conf['egov-config']['serializers-timezone-in-ist'] %}
        - name: SPRING_KAFKA_CONSUMER_VALUE_DESERIALIZER
          value: org.egov.tracer.kafka.deserializer.ISTTimeZoneHashMapDeserializer
        - name: SPRING_KAFKA_PRODUCER_VALUE_SERIALIZER
          value: org.egov.tracer.kafka.serializer.ISTTimeZoneJsonSerializer
{% endif %}
        - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
          valueFrom:
            configMapKeyRef:
              name: egov-config
              key: kafka-brokers
        - name: APP_TIMEZONE
          valueFrom:
            configMapKeyRef:
              name: egov-config
              key: timezone
        - name: JAVA_OPTS
          value: "{{conf['egf-voucher-workflow']['heap'] or '-Xmx64m -Xms64m'}}"
        - name: SPRING_JPA_SHOW_SQL
          value: "{{conf['egov-config']['spring-jpa-show-sql']}}"
        - name: SERVER_PORT
          value: "8080"
        - name: FLYWAY_ENABLED
          value: "false"
        resources:
          requests:
            memory: "64Mi"
          limits:
            memory: "{{ conf['egf-voucher-workflow']['memory_limits'] or "256Mi"}}"
