apiVersion: v1
kind: Service
metadata:
  name: egf-master
  namespace: egov
  labels:
    app: egf-master
    group: financials
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: egf-master
    group: financials
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: egf-master
  namespace: egov
spec:
  replicas: {{conf['egf-master']['replicas']}}
  template:
    metadata:
      labels:
        app: egf-master
        group: financials
      annotations:
        pod.beta.kubernetes.io/init-containers: '[
          {
            "name": "egf-master-db-migration",
            "image": "{{conf["egf-master"]["db_migration_image"]}}",
            "env": [
              {"name": "DB_URL", "value": "{{ conf['egf-master']['db-url']}}"},
              {"name": "SCHEMA_TABLE", "value": "egf_master_schema"},
              {"name": "FLYWAY_USER", "valueFrom": {"secretKeyRef": {"name": "db", "key": "flyway-username"}}},
              {"name": "FLYWAY_PASSWORD", "valueFrom": {"secretKeyRef": {"name": "db", "key": "flyway-password"}}},
              {"name": "FLYWAY_LOCATIONS", "valueFrom": {"configMapKeyRef": {"name": "egov-config", "key": "flyway-locations"}}}
            ],
            "imagePullPolicy": "IfNotPresent"
          }
        ]'
    spec:
      containers:
      - name: egf-master
        image: {{conf['egf-master']['images'][0]}}
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_URL
          value: {{ conf['egf-master']['db-url'] }}
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: db
              key: username
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db
              key: password
        - name: KAFKA_TOPICS_EGF_MASTERS_VALIDATED_KEY
          value: egov.egf.masters.bank.validated.key
        - name: KAFKA_TOPICS_EGF_MASTERS_VALIDATED_TOPIC
          value: egov.egf.masters.validated.topic
        - name: KAFKA_TOPICS_EGF_MASTERS_VALIDATED_GROUP
          value: egov.egf.masters.validated.group
        - name: KAFKA_TOPICS_EGF_MASTERS_VALIDATED_ID
          value: egov.egf.masters.bank.validated.id
        - name: KAFKA_TOPICS_EGF_MASTERS_COMPLETED_TOPIC
          value: egov.egf.masters.completed
        - name: KAFKA_TOPICS_EGF_MASTERS_COMPLETED_GROUP
          value: egov.egf.masters.completed.group
        - name: KAFKA_TOPICS_EGF_MASTERS_BANK_VALIDATED_KEY
          value: egov.egf.masters.bank.validated.key
        - name: KAFKA_TOPICS_EGF_MASTERS_BANKBRANCH_VALIDATED_KEY
          value: egov.egf.masters.bankbranch.validated.key
        - name: KAFKA_TOPICS_EGF_MASTERS_BANKACCOUNT_VALIDATED_KEY
          value: egov.egf.masters.bankaccount.validated.key
        - name: KAFKA_TOPICS_EGF_MASTERS_ACCOUNTCODEPURPOSE_VALIDATED_KEY
          value: egov.egf.masters.accountcodepurpose.validated.key
        - name: KAFKA_TOPICS_EGF_MASTERS_ACCOUNTDETAILKEY_VALIDATED_KEY
          value: egov.egf.masters.accountdetailkey.validated.key
        - name: KAFKA_TOPICS_EGF_MASTERS_ACCOUNTDETAILTYPE_VALIDATED_KEY
          value: egov.egf.masters.accountdetailtype.validated.key
        - name: KAFKA_TOPICS_EGF_MASTERS_ACCOUNTENTITY_VALIDATED_KEY
          value: egov.egf.masters.accountentity.validated.key
        - name: KAFKA_TOPICS_EGF_MASTERS_BUDGETGROUP_VALIDATED_KEY
          value: egov.egf.masters.budgetgroup.validated.key
        - name: KAFKA_TOPICS_EGF_MASTERS_CHARTOFACCOUNT_VALIDATED_KEY
          value: egov.egf.masters.chartofaccount.validated.key
        - name: KAFKA_TOPICS_EGF_MASTERS_CHARTOFACCOUNTDETAIL_VALIDATED_KEY
          value: egov.egf.masters.chartofaccountdetail.validated.key
        - name: KAFKA_TOPICS_EGF_MASTERS_FINANCIALYEAR_VALIDATED_KEY
          value: egov.egf.masters.financialyear.validated.key
        - name: KAFKA_TOPICS_EGF_MASTERS_FISCALPERIOD_VALIDATED_KEY
          value: egov.egf.masters.fiscalperiod.validated.key
        - name: KAFKA_TOPICS_EGF_MASTERS_FUNCTIONARY_VALIDATED_KEY
          value: egov.egf.masters.functionary.validated.key
        - name: KAFKA_TOPICS_EGF_MASTERS_FUNCTION_VALIDATED_KEY
          value: egov.egf.masters.function.validated.key
        - name: KAFKA_TOPICS_EGF_MASTERS_FUND_VALIDATED_KEY
          value: egov.egf.masters.fund.validated.key
        - name: KAFKA_TOPICS_EGF_MASTERS_FUNDSOURCE_VALIDATED_KEY
          value: egov.egf.masters.fundsource.validated.key
        - name: KAFKA_TOPICS_EGF_MASTERS_SCHEME_VALIDATED_KEY
          value: egov.egf.masters.scheme.validated.key
        - name: KAFKA_TOPICS_EGF_MASTERS_SUBSCHEME_VALIDATED_KEY
          value: egov.egf.masters.subscheme.validated.key
        - name: KAFKA_TOPICS_EGF_MASTERS_SUPPLIER_VALIDATED_KEY
          value: egov.egf.masters.supplierfund.validated.key
        - name: KAFKA_TOPICS_EGF_MASTERS_BANK_COMPLETED_KEY
          value: egov.egf.masters.bank.completed.key
        - name: KAFKA_TOPICS_EGF_MASTERS_BANKBRANCH_COMPLETED_KEY
          value: egov.egf.masters.bankbranch.completed.key
        - name: KAFKA_TOPICS_EGF_MASTERS_BANKACCOUNT_COMPLETED_KEY
          value: egov.egf.masters.bankaccount.completed.key
        - name: KAFKA_TOPICS_EGF_MASTERS_ACCOUNTCODEPURPOSE_COMPLETED_KEY
          value: egov.egf.masters.accountcodepurpose.completed.key
        - name: KAFKA_TOPICS_EGF_MASTERS_ACCOUNTDETAILKEY_COMPLETED_KEY
          value: egov.egf.masters.accountdetailkey.completed.key
        - name: KAFKA_TOPICS_EGF_MASTERS_ACCOUNTDETAILTYPE_COMPLETED_KEY
          value: egov.egf.masters.accountdetailtype.completed.key
        - name: KAFKA_TOPICS_EGF_MASTERS_ACCOUNTENTITY_COMPLETED_KEY
          value: egov.egf.masters.accountentity.completed.key
        - name: KAFKA_TOPICS_EGF_MASTERS_BUDGETGROUP_COMPLETED_KEY
          value: egov.egf.masters.budgetgroup.completed.key
        - name: KAFKA_TOPICS_EGF_MASTERS_CHARTOFACCOUNT_COMPLETED_KEY
          value: egov.egf.masters.chartofaccount.completed.key
        - name: KAFKA_TOPICS_EGF_MASTERS_CHARTOFACCOUNTDETAIL_COMPLETED_KEY
          value: egov.egf.masters.chartofaccountdetail.completed.key
        - name: KAFKA_TOPICS_EGF_MASTERS_FINANCIALYEAR_COMPLETED_KEY
          value: egov.egf.masters.financialyear.completed.key
        - name: KAFKA_TOPICS_EGF_MASTERS_FISCALPERIOD_COMPLETED_KEY
          value: egov.egf.masters.fiscalperiod.completed.key
        - name: KAFKA_TOPICS_EGF_MASTERS_FUNCTIONARY_COMPLETED_KEY
          value: egov.egf.masters.functionary.completed.key
        - name: KAFKA_TOPICS_EGF_MASTERS_FUNCTION_COMPLETED_KEY
          value: egov.egf.masters.function.completed.key
        - name: KAFKA_TOPICS_EGF_MASTERS_FUND_COMPLETED_KEY
          value: egov.egf.masters.fund.completed.key
        - name: KAFKA_TOPICS_EGF_MASTERS_FUNDSOURCE_COMPLETED_KEY
          value: egov.egf.masters.fundsource.completed.key
        - name: KAFKA_TOPICS_EGF_MASTERS_SCHEME_COMPLETED_KEY
          value: egov.egf.masters.scheme.completed.key
        - name: KAFKA_TOPICS_EGF_MASTERS_SUBSCHEME_COMPLETED_KEY
          value: egov.egf.masters.subscheme.completed.key
        - name: KAFKA_TOPICS_EGF_MASTERS_SUPPLIER_COMPLETED_KEY
          value: egov.egf.masters.supplier.completed.key
        - name: FLYWAY_ENABLED
          value: "false"
        - name: ES_HOST
          valueFrom:
            configMapKeyRef:
              name: egov-config
              key: es-host
        - name: ES_TRANSPORT_PORT
          value: "9300"
        - name: ES_CLUSTER_NAME
          value: egov_es_cluster
        - name: EGF_MASTER_HOST_URL
          value: "{{conf['egov-service-host']['egf-master']}}"
        - name: SPRING_KAFKA_CONSUMER_KEY_DESERIALIZER
          value: org.apache.kafka.common.serialization.StringDeserializer
        - name: SPRING_KAFKA_CONSUMER_GROUP_ID
          value: egf-master
        - name: SPRING_KAFKA_PRODUCER_KEY_SERIALIZER
          value: org.apache.kafka.common.serialization.StringSerializer
{% if conf['egov-config']['serializers-timezone-in-ist'] %}
        - name: SPRING_KAFKA_CONSUMER_VALUE_DESERIALIZER
          value: org.egov.tracer.kafka.deserializer.ISTTimeZoneHashMapDeserializer
        - name: SPRING_KAFKA_PRODUCER_VALUE_SERIALIZER
          value: org.egov.tracer.kafka.serializer.ISTTimeZoneJsonSerializer
{% endif %}
        - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
          valueFrom:
            configMapKeyRef:
              name: egov-config
              key: kafka-brokers
        - name: APP_TIMEZONE
          valueFrom:
            configMapKeyRef:
              name: egov-config
              key: timezone
        - name: JAVA_OPTS
          value: "{{conf['egf-master']['heap'] or '-Xmx192m -Xms192m'}}"
        - name: SERVER_PORT
          value: "8080"
        resources:
          requests:
            memory: "64Mi"
          limits:
            memory: "{{ conf['egf-master']['memory_limits'] or "512Mi"}}"
