apiVersion: v1
kind: Service
metadata:
  name: egf-bill
  namespace: egov
  labels:
    app: egf-bill
    group: financials
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: egf-bill
    group: financials
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: egf-bill
  namespace: egov
spec:
  replicas: {{conf['egf-bill']['replicas']}}
  template:
    metadata:
      labels:
        app: egf-bill
        group: financials
      annotations:
        pod.beta.kubernetes.io/init-containers: '[
          {
            "name": "egf-bill-db-migration",
            "image": "{{conf["egf-bill"]["db_migration_image"]}}",
            "env": [
              {"name": "DB_URL", "valueFrom": {"configMapKeyRef": {"name": "egov-config", "key": "db-url"}}},
              {"name": "SCHEMA_TABLE", "value": "egf_bill_schema"},
              {"name": "FLYWAY_USER", "valueFrom": {"secretKeyRef": {"name": "db", "key": "flyway-username"}}},
              {"name": "FLYWAY_PASSWORD", "valueFrom": {"secretKeyRef": {"name": "db", "key": "flyway-password"}}},
              {"name": "FLYWAY_LOCATIONS", "valueFrom": {"configMapKeyRef": {"name": "egov-config", "key": "flyway-locations"}}}
            ],
            "imagePullPolicy": "IfNotPresent"
          }
        ]'
    spec:
      containers:
      - name: egf-bill
        image: {{conf['egf-bill']['images'][0]}}
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            configMapKeyRef:
              name: egov-config
              key: db-url
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: db
              key: username
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db
              key: password
        - name: SPRING_DATASOURCE_TOMCAT_DEFAULT_READ_ONLY
          value: "false"
        - name: KAFKA_TOPICS_EGF_BILL_VALIDATED_TOPIC
          value: egov.egf.bill.validated.topic
        - name: KAFKA_TOPICS_EGF_BILL_VALIDATED_GROUP
          value: egov.egf.bill.validated.group
        - name: KAFKA_TOPICS_EGF_BILL_VALIDATED_ID
          value: egov.egf.bill.validated.id
        - name: KAFKA_TOPICS_EGF_BILL_COMPLETED_TOPIC
          value: egov.egf.bill.completed
        - name: KAFKA_TOPICS_EGF_BILL_COMPLETED_GROUP
          value: egov.egf.bill.completed.group
        - name: KAFKA_TOPICS_EGF_BILL_VALIDATED_KEY
          value: egov.egf.bill.validated.key
        - name: KAFKA_TOPICS_EGF_BILL_BILL_REGISTER_VALIDATED_KEY
          value: egov.egf.bill.bill.register.validated.key
        - name: KAFKA_TOPICS_EGF_BILL_BILLCHECKLIST_VALIDATED_KEY
          value: egov.egf.bill.billchecklist.validated.key
        - name: KAFKA_TOPICS_EGF_BILL_BILL_DETAIL_VALIDATED_KEY
          value: egov.egf.bill.bill.detail.validated.key
        - name: KAFKA_TOPICS_EGF_BILL_BILL_PAYEEDETAIL_VALIDATED_KEY
          value: egov.egf.bill.bill.payeedetail.validated.key
        - name: KAFKA_TOPICS_EGF_BILL_BILL_CHECKLIST_VALIDATED_KEY
          value: egov.egf.bill.bill.checklist.validated.key
        - name: KAFKA_TOPICS_EGF_BILL_COMPLETED_KEY
          value: egov.egf.bill.completed.key
        - name: KAFKA_TOPICS_EGF_BILL_BILL_REGISTER_COMPLETED_KEY
          value: egov.egf.bill.bill.register.completed.key
        - name: KAFKA_TOPICS_EGF_BILL_BILLCHECKLIST_COMPLETED_KEY
          value: egov.egf.bill.billchecklist.completed.key
        - name: KAFKA_TOPICS_EGF_BILL_BILL_DETAIL_COMPLETED_KEY
          value: egov.egf.bill.bill.detail.completed.key
        - name: KAFKA_TOPICS_EGF_BILL_BILL_PAYEEDETAIL_COMPLETED_KEY
          value: egov.egf.bill.bill.payeedetail.completed.key
        - name: KAFKA_TOPICS_EGF_BILL_BILL_CHECKLIST_COMPLETED_KEY
          value: egov.egf.bill.bill.checklist.completed.key
        - name: SPRING_KAFKA_CONSUMER_KEY_DESERIALIZER
          value: org.apache.kafka.common.serialization.StringDeserializer
        - name: SPRING_KAFKA_CONSUMER_GROUP_ID
          value: egf-bill
        - name: SPRING_KAFKA_PRODUCER_KEY_SERIALIZER
          value: org.apache.kafka.common.serialization.StringSerializer
{% if conf['egov-config']['serializers-timezone-in-ist'] %}
        - name: SPRING_KAFKA_CONSUMER_VALUE_DESERIALIZER
          value: org.egov.tracer.kafka.deserializer.ISTTimeZoneHashMapDeserializer
        - name: SPRING_KAFKA_PRODUCER_VALUE_SERIALIZER
          value: org.egov.tracer.kafka.serializer.ISTTimeZoneJsonSerializer
{% endif %}
        - name: EGF_MASTER_HOST_URL
          value: "{{conf['egov-service-host']['egf-master']}}"
        - name: EGF_BILL_HOST_URL
          value: "{{conf['egov-service-host']['egf-bill']}}"
        - name: EGOV_SERVICES_BOUNDARY_HOST
          value: "{{conf['egov-service-host']['egov-location']}}"
        - name: EGOV_SERVICES_EGOV_MDMS_HOSTNAME
          value: "{{conf['egov-service-host']['egov-mdms-service']}}"
        - name: EGOV_SERVICES_EGOV_IDGEN_HOSTNAME
          value: "{{conf['egov-service-host']['egov-idgen']}}"
        - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
          valueFrom:
            configMapKeyRef:
              name: egov-config
              key: kafka-brokers
        - name: APP_TIMEZONE
          valueFrom:
            configMapKeyRef:
              name: egov-config
              key: timezone
        - name: JAVA_OPTS
          value: "{{conf['egf-bill']['heap'] or '-Xmx64m -Xms64m'}}"
        - name: SPRING_JPA_SHOW_SQL
          value: "{{conf['egov-config']['spring-jpa-show-sql']}}"
        - name: SERVER_PORT
          value: "8080"
        - name: FLYWAY_ENABLED
          value: "false"
        resources:
          requests:
            memory: "64Mi"
          limits:
            memory: "{{ conf['egf-bill']['memory_limits'] or "256Mi"}}"
