apiVersion: v1
kind: Service
metadata:
  name: egf-masters
  namespace: egov
  labels:
    app: egf-masters
    group: financials
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: egf-masters
    group: financials
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: egf-masters
  namespace: egov
spec:
  replicas: {{conf['egf-masters']['replicas']}}
  template:
    metadata:
      labels:
        app: egf-masters
        group: financials
      annotations:
        pod.beta.kubernetes.io/init-containers: '[
        {% if conf["egf-masters"]["env_specific_db_migration_image"] %}
          {
            "name": "egf-masters-env-specific-db-migration",
            "image": "{{conf["egf-masters"]["env_specific_db_migration_image"]}}",
            "command": ["sh", "-c", "cp -R /egov/db/migration/financials/egf-masters/* /env_specific_db_migration/"],
            "volumeMounts": [
              {
                "mountPath": "/env_specific_db_migration",
                "name": "env-specific-db-migration"
              }
            ],
            "imagePullPolicy": "Always"
          },
        {% endif %}
          {
            "name": "egf-masters-db-migration",
            "image": "{{conf["egf-masters"]["db_migration_image"]}}",
            "env": [
              {"name": "DB_URL", "valueFrom": {"configMapKeyRef": {"name": "egov-config", "key": "db-url"}}},
              {"name": "SCHEMA_TABLE", "value": "egf_masters_schema"},
              {"name": "FLYWAY_USER", "valueFrom": {"secretKeyRef": {"name": "db", "key": "flyway-username"}}},
              {"name": "FLYWAY_PASSWORD", "valueFrom": {"secretKeyRef": {"name": "db", "key": "flyway-password"}}},
              {"name": "FLYWAY_LOCATIONS", "valueFrom": {"configMapKeyRef": {"name": "egov-config", "key": "flyway-locations"}}}
            ],
            "volumeMounts": [
              {
                "mountPath": "/env_specific_db_migration",
                "name": "env-specific-db-migration"
              }
            ],
            "imagePullPolicy": "IfNotPresent"
          }
        ]'
    spec:
      containers:
      - name: egf-masters
        image: {{conf['egf-masters']['images'][0]}}
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            configMapKeyRef:
              name: egov-config
              key: db-url
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: db
              key: username
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db
              key: password
        - name: SPRING_DATASOURCE_TOMCAT_INITIAL_SIZE
          valueFrom:
            configMapKeyRef:
              name: egov-config
              key: spring-datasource-tomcat-initialSize
        - name: SERVER_PORT
          value: "8080"
        - name: FLYWAY_ENABLED
          value: "false"
        - name: KAFKA_CONFIG_BOOTSTRAP_SERVER_CONFIG
          valueFrom:
            configMapKeyRef:
              name: egov-config
              key: kafka-brokers
        - name: KAFKA_TOPICS_EGF_MASTERS_VALIDATED_TOPIC
          value: egov.egf.masters.validated.topic
        - name: KAFKA_TOPICS_EGF_MASTERS_VALIDATED_GROUP
          value: egov.egf.masters.validated.group
        - name: KAFKA_TOPICS_EGF_MASTERS_VALIDATED_ID
          value: egov.egf.masters.bank.validated.id
        - name: KAFKA_TOPICS_EGF_MASTERS_COMPLETED_TOPIC
          value: egov.egf.masters.completed
        - name: KAFKA_TOPICS_EGF_MASTERS_COMPLETED_GROUP
          value: egov.egf.masters.completed.group
        - name: KAFKA_TOPICS_EGF_MASTERS_BANK_VALIDATED_KEY
          value: egov.egf.masters.bank.validated.key
        - name: KAFKA_TOPICS_EGF_MASTERS_BANKBRANCH_VALIDATED_KEY
          value: egov.egf.masters.bankbranch.validated.key
        - name: KAFKA_TOPICS_EGF_MASTERS_BANKACCOUNT_VALIDATED_KEY
          value: egov.egf.masters.bankaccount.validated.key
        - name: KAFKA_TOPICS_EGF_MASTERS_ACCOUNTCODEPURPOSE_VALIDATED_KEY
          value: egov.egf.masters.accountcodepurpose.validated.key
        - name: KAFKA_TOPICS_EGF_MASTERS_ACCOUNTDETAILKEY_VALIDATED_KEY
          value: egov.egf.masters.accountdetailkey.validated.key
        - name: KAFKA_TOPICS_EGF_MASTERS_ACCOUNTDETAILTYPE_VALIDATED_KEY
          value: egov.egf.masters.accountdetailtype.validated.key
        - name: KAFKA_TOPICS_EGF_MASTERS_ACCOUNTENTITY_VALIDATED_KEY
          value: egov.egf.masters.accountentity.validated.key
        - name: KAFKA_TOPICS_EGF_MASTERS_BUDGETGROUP_VALIDATED_KEY
          value: egov.egf.masters.budgetgroup.validated.key
        - name: KAFKA_TOPICS_EGF_MASTERS_CHARTOFACCOUNT_VALIDATED_KEY
          value: egov.egf.masters.chartofaccount.validated.key
        - name: KAFKA_TOPICS_EGF_MASTERS_CHARTOFACCOUNTDETAIL_VALIDATED_KEY
          value: egov.egf.masters.chartofaccountdetail.validated.key
        - name: KAFKA_TOPICS_EGF_MASTERS_FINANCIALYEAR_VALIDATED_KEY
          value: egov.egf.masters.financialyear.validated.key
        - name: KAFKA_TOPICS_EGF_MASTERS_FISCALPERIOD_VALIDATED_KEY
          value: egov.egf.masters.fiscalperiod.validated.key
        - name: KAFKA_TOPICS_EGF_MASTERS_FUNCTIONARY_VALIDATED_KEY
          value: egov.egf.masters.functionary.validated.key
        - name: KAFKA_TOPICS_EGF_MASTERS_FUNCTION_VALIDATED_KEY
          value: egov.egf.masters.function.validated.key
        - name: KAFKA_TOPICS_EGF_MASTERS_FUND_VALIDATED_KEY
          value: egov.egf.masters.fund.validated.key
        - name: KAFKA_TOPICS_EGF_MASTERS_FUNDSOURCE_VALIDATED_KEY
          value: egov.egf.masters.fundsource.validated.key
        - name: KAFKA_TOPICS_EGF_MASTERS_SCHEME_VALIDATED_KEY
          value: egov.egf.masters.scheme.validated.key
        - name: KAFKA_TOPICS_EGF_MASTERS_SUBSCHEME_VALIDATED_KEY
          value: egov.egf.masters.subscheme.validated.key
        - name: KAFKA_TOPICS_EGF_MASTERS_SUPPLIER_VALIDATED_KEY
          value: egov.egf.masters.supplierfund.validated.key
        - name: KAFKA_TOPICS_EGF_MASTERS_BANK_COMPLETED_KEY
          value: egov.egf.masters.bank.completed.key
        - name: KAFKA_TOPICS_EGF_MASTERS_BANKBRANCH_COMPLETED_KEY
          value: egov.egf.masters.bankbranch.completed.key
        - name: KAFKA_TOPICS_EGF_MASTERS_BANKACCOUNT_COMPLETED_KEY
          value: egov.egf.masters.bankaccount.completed.key
        - name: KAFKA_TOPICS_EGF_MASTERS_ACCOUNTCODEPURPOSE_COMPLETED_KEY
          value: egov.egf.masters.accountcodepurpose.completed.key
        - name: KAFKA_TOPICS_EGF_MASTERS_ACCOUNTDETAILKEY_COMPLETED_KEY
          value: egov.egf.masters.accountdetailkey.completed.key
        - name: KAFKA_TOPICS_EGF_MASTERS_ACCOUNTDETAILTYPE_COMPLETED_KEY
          value: egov.egf.masters.accountdetailtype.completed.key
        - name: KAFKA_TOPICS_EGF_MASTERS_ACCOUNTENTITY_COMPLETED_KEY
          value: egov.egf.masters.accountentity.completed.key
        - name: KAFKA_TOPICS_EGF_MASTERS_BUDGETGROUP_COMPLETED_KEY
          value: egov.egf.masters.budgetgroup.completed.key
        - name: KAFKA_TOPICS_EGF_MASTERS_CHARTOFACCOUNT_COMPLETED_KEY
          value: egov.egf.masters.chartofaccount.completed.key
        - name: KAFKA_TOPICS_EGF_MASTERS_CHARTOFACCOUNTDETAIL_COMPLETED_KEY
          value: egov.egf.masters.chartofaccountdetail.completed.key
        - name: KAFKA_TOPICS_EGF_MASTERS_FINANCIALYEAR_COMPLETED_KEY
          value: egov.egf.masters.financialyear.completed.key
        - name: KAFKA_TOPICS_EGF_MASTERS_FISCALPERIOD_COMPLETED_KEY
          value: egov.egf.masters.fiscalperiod.completed.key
        - name: KAFKA_TOPICS_EGF_MASTERS_FUNCTIONARY_COMPLETED_KEY
          value: egov.egf.masters.functionary.completed.key
        - name: KAFKA_TOPICS_EGF_MASTERS_FUNCTION_COMPLETED_KEY
          value: egov.egf.masters.function.completed.key
        - name: KAFKA_TOPICS_EGF_MASTERS_FUND_COMPLETED_KEY
          value: egov.egf.masters.fund.completed.key
        - name: KAFKA_TOPICS_EGF_MASTERS_FUNDSOURCE_COMPLETED_KEY
          value: egov.egf.masters.fundsource.completed.key
        - name: KAFKA_TOPICS_EGF_MASTERS_SCHEME_COMPLETED_KEY
          value: egov.egf.masters.scheme.completed.key
        - name: KAFKA_TOPICS_EGF_MASTERS_SUBSCHEME_COMPLETED_KEY
          value: egov.egf.masters.subscheme.completed.key
        - name: KAFKA_TOPICS_EGF_MASTERS_SUPPLIER_COMPLETED_KEY
          value: egov.egf.masters.supplier.completed.key
        - name: KAFKA_CONSUMER_CONFIG_GROUP_ID
          value: financial_masters_group
        - name: JAVA_OPTS
          value: "{{conf['egf-masters']['heap'] or '-Xmx64m -Xms64m'}}"
        - name: APP_TIMEZONE
          valueFrom:
            configMapKeyRef:
              name: egov-config
              key: timezone
        - name: SPRING_JPA_SHOW_SQL
          value: "{{conf['egov-config']['spring-jpa-show-sql']}}"
{% if conf['egf-masters']['memory_limits'] %}
        resources:
          requests:
            memory: "64Mi"
          limits:
            memory: "{{ conf['egf-masters']['memory_limits'] }}"
{% endif %}
      volumes:
      - name: env-specific-db-migration
        emptyDir: {}
{% if conf['egov-docker-registry-secret'] %}
      imagePullSecrets:
      - name: regsecret
      - name: allvyregsecret
{% endif %}
