---
- name: Install lsb_release
  yum: name=redhat-lsb-core state=present
  when: ansible_os_family == "RedHat"
  become: true

- name: Reread ansible_lsb facts
  setup: filter=ansible_lsb*

# - name: Enable RHEL extras repository
#   yum_repository:
#     name: rhui-REGION-rhel-server-extras
#     description: Red Hat Enterprise Linux Server 7 Extra(RPMs)
#     baseurl: https://rhui2-cds01.REGION.aws.ce.redhat.com/pulp/mirror/content/dist/rhel/rhui/server/7/$releasever/$basearch/extras/os
#     enabled: yes
#     gpgcheck: no
#   when: ansible_os_family == "RedHat" and ansible_lsb.major_release|int >= 7
#   become: true

- name: Install ntp
  yum: name=ntp state=present
  become: true

- name: Start and enable ntpd
  systemd: name=ntpd daemon_reload=yes state=started enabled=yes
  become: true

- name: Stop and disable firewall
  systemd: name=firewalld daemon_reload=yes state=stopped enabled=no
  register: unused_disable
  failed_when: "unused_disable|failed and ('find' not in unused_disable.msg and 'found' not in unused_disable.msg)"
  become: true

- name: Create keys directory to store keys
  become: true
  file: path=/etc/kubernetes/keys state=directory mode=0755

- name: Copy certificate authority keys
  become: true
  copy: src={{ item }} dest=/etc/kubernetes/keys/{{ item }} mode=0644
  with_items:
    - ca.pem
    - ca-key.pem
