apiVersion: v1
kind: Service
metadata:
  name: collection-masters
  namespace: egov
  labels:
    app: collection-masters
    group: collections
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: collection-masters
    group: collections
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: collection-masters
  namespace: egov
spec:
  replicas: {{conf['collection-masters']['replicas']}}
  template:
    metadata:
      labels:
        app: collection-masters
        group: collections
      annotations:
        pod.beta.kubernetes.io/init-containers: '[
          {
            "name": "collection-masters-db-migration",
            "image": "{{conf["collection-masters"]["db_migration_image"]}}",
            "env": [
              {"name": "DB_URL", "value": "{{conf['collection-masters']['db-url']}}"},
              {"name": "SCHEMA_TABLE", "value": "egov_collection_masters_schema"},
              {"name": "FLYWAY_USER", "valueFrom": {"secretKeyRef": {"name": "db", "key": "flyway-username"}}},
              {"name": "FLYWAY_PASSWORD", "valueFrom": {"secretKeyRef": {"name": "db", "key": "flyway-password"}}},
              {"name": "FLYWAY_LOCATIONS", "valueFrom": {"configMapKeyRef": {"name": "egov-config", "key": "flyway-locations"}}}
            ],
            "imagePullPolicy": "IfNotPresent"
          }
        ]'
    spec:
      containers:
      - name: collection-masters
        image: {{conf['collection-masters']['images'][0]}}
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            configMapKeyRef:
              name: egov-config
              key: db-url
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: db
              key: username
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db
              key: password
        - name: SPRING_DATASOURCE_TOMCAT_INITIAL_SIZE
          valueFrom:
            configMapKeyRef:
              name: egov-config
              key: spring-datasource-tomcat-initialSize
        - name: SERVER_PORT
          value: "8080"
        - name: FLYWAY_ENABLED
          value: "false"
        - name: USER_SERVICE_URL
          value: "{{conf['egov-service-host']['egov-user-egov']}}"
        - name: JAVA_OPTS
          value: "{{conf['collection-masters']['heap'] or '-Xmx64m -Xms64m'}}"
        - name: APP_TIMEZONE
          valueFrom:
            configMapKeyRef:
              name: egov-config
              key: timezone
        - name: SPRING_JPA_SHOW_SQL
          value: "{{conf['egov-config']['spring-jpa-show-sql']}}"
        - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
          valueFrom:
            configMapKeyRef:
              name: egov-config
              key: kafka-brokers
        - name: KAFKA_TOPICS_BANKACCOUNTSERVICEMAPPING_CREATE_NAME
          value: egov.collectionmasters.bankaccountservicemapping-create
        - name: KAFKA_TOPICS_BANKACCOUNTSERVICEMAPPING_CREATE_KEY
          value: bankaccountservicemapping-create
        - name: SPRING_KAFKA_CONSUMER_VALUE_DESERIALIZER
          value: org.egov.collection.consumer.HashMapDeserializer
        - name: SPRING_KAFKA_CONSUMER_KEY_DESERIALIZER
          value: org.apache.kafka.common.serialization.StringDeserializer
        - name: SPRING_KAFKA_CONSUMER_GROUP_ID
          value: collectionmasters-persist
        - name: SPRING_KAFKA_PRODUCER_KEY_SERIALIZER
          value: org.apache.kafka.common.serialization.StringSerializer
        - name: SPRING_KAFKA_PRODUCER_VALUE_SERIALIZER
          value: org.springframework.kafka.support.serializer.JsonSerializer
        resources:
          requests:
            memory: "64Mi"
          limits:
            memory: "{{ conf['collection-masters']['memory_limits'] or "256Mi"}}"
