apiVersion: v1
kind: Service
metadata:
  name: collection-notification
  namespace: egov
  labels:
    app: collection-notification
    group: collections
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: collection-notification
    group: collections
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: collection-notification
  namespace: egov
spec:
  replicas: {{conf['collection-notification']['replicas']}}
  template:
    metadata:
      labels:
        app: collection-notification
        group: collections
    spec:
      containers:
      - name: collection-notification
        image: {{conf['collection-notification']['images'][0]}}
        ports:
        - containerPort: 8080
        env:
        - name: KAFKA_TOPICS_NOTIFICATION_SMS_ID
          value: notification.sms
        - name: KAFKA_TOPICS_NOTIFICATION_EMAIL_KEY
          value: email-notification
        - name: KAFKA_TOPICS_NOTIFICATION_SMS_GROUP
          value: sms-group1
        - name: SPRING_KAFKA_CONSUMER_GROUP_ID
          value: collection.notification.group
        - name: SPRING_KAFKA_CONSUMER_VALUE_DESERIALIZER
          value: org.egov.collection.notification.consumer.HashMapDeserializer
        - name: SPRING_KAFKA_CONSUMER_KEY_DESERIALIZER
          value: org.apache.kafka.common.serialization.StringDeserializer
        - name: SPRING_KAFKA_PRODUCER_KEY_SERIALIZER
          value: org.apache.kafka.common.serialization.StringSerializer
        - name: SPRING_KAFKA_PRODUCER_VALUE_SERIALIZER
          value: org.springframework.kafka.support.serializer.JsonSerializer
        - name: EGOV_TENANT_HOST
          value: "{{conf['egov-service-host']['tenant']}}"
        - name: EGOV_COLLECTION_SERVICES_HOST
          value: "{{conf['egov-service-host']['collection-services']}}"
        - name: EGOV_SERVICES_COMMON_MASTERS_HOST
          value: "{{conf['egov-service-host']['egov-common-masters']}}"
        - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
          valueFrom:
            configMapKeyRef:
              name: egov-config
              key: kafka-brokers
        - name: APP_TIMEZONE
          valueFrom:
            configMapKeyRef:
              name: egov-config
              key: timezone
        - name: JAVA_OPTS
          value: "{{conf['collection-notification']['heap'] or '-Xmx64m -Xms64m'}}"
        - name: SPRING_JPA_SHOW_SQL
          value: "{{conf['egov-config']['spring-jpa-show-sql']}}"
        - name: SERVER_PORT
          value: "8080"
        - name: FLYWAY_ENABLED
          value: "false"
        resources:
          requests:
            memory: "64Mi"
          limits:
            memory: "{{ conf['collection-notification']['memory_limits'] or "256Mi"}}"
