apiVersion: v1
kind: Service
metadata:
  name: swm-admin
  namespace: swmpoc
  labels:
    app: swm-admin
spec:
  ports:
  - port: 3005
    targetPort: 3005
    protocol: TCP
  selector:
    app: swm-admin
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: swm-admin
  namespace: swmpoc
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: swm-admin
    spec:
      containers:
      - name: swm-admin
        image: {{conf['swm-admin']['images'][0]}}
        ports:
        - containerPort: 3005
        env:
        resources:
          requests:
            memory: "512Mi"
          limits:
            memory: {{conf['swm-admin']['memory_limits'] or "512Mi"}}