apiVersion: v1
kind: Service
metadata:
  name: pt-calculator
  namespace: egov
  labels:
    app: pt-calculator
    group: property
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: pt-calculator
    group: property
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pt-calculator
  namespace: egov
spec:
  replicas: {{conf['pt-calculator']['replicas']}}
  template:
    metadata:
      labels:
        app: pt-calculator
        group: property
      annotations:
        pod.beta.kubernetes.io/init-containers: '[
          {
            "name": "pt-calculator-db-migration",
            "image": "{{conf["pt-calculator"]["db_migration_image"]}}",
            "env": [
              {"name": "DB_URL", "valueFrom": {"configMapKeyRef": {"name": "egov-config", "key": "db-url"}}},
              {"name": "SCHEMA_TABLE", "value": "pt_calculator_schema"},
              {"name": "FLYWAY_USER", "valueFrom": {"secretKeyRef": {"name": "db", "key": "flyway-username"}}},
              {"name": "FLYWAY_PASSWORD", "valueFrom": {"secretKeyRef": {"name": "db", "key": "flyway-password"}}},
              {"name": "FLYWAY_LOCATIONS", "valueFrom": {"configMapKeyRef": {"name": "egov-config", "key": "flyway-locations"}}}
            ],
            "imagePullPolicy": "IfNotPresent"
          }
        ]'
    spec:
      containers:
      - name: pt-calculator
        image: {{conf['pt-calculator']['images'][0]}}
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            configMapKeyRef:
              name: egov-config
              key: db-url
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: db
              key: username
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db
              key: password
        - name: SPRING_DATASOURCE_TOMCAT_INITIAL_SIZE
          valueFrom:
            configMapKeyRef:
              name: egov-config
              key: spring-datasource-tomcat-initialSize
        - name: SERVER_PORT
          value: "8080"
        - name: EGOV_SERVICES_PT_PROPERTY_HOSTNAME
          value: "{{conf['egov-service-host']['pt-property']}}"
        - name: FLYWAY_ENABLED
          value: "false"
        - name: APP_TIMEZONE
          valueFrom:
            configMapKeyRef:
              name: egov-config
              key: timezone
        - name: SPRING_JPA_SHOW_SQL
          value: "{{conf['egov-config']['spring-jpa-show-sql']}}"
        resources:
          requests:
            memory: "64Mi"
          limits:
            memory: "{{ conf['pt-calculator']['memory_limits'] or "256Mi"}}"
