apiVersion: v1
kind: Service
metadata:
  name: pt-tax-enrichment
  namespace: egov
  labels:
    app: pt-tax-enrichment
    group: property
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: pt-tax-enrichment
    group: property
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pt-tax-enrichment
  namespace: egov
spec:
  replicas: {{conf['pt-tax-enrichment']['replicas']}}
  template:
    metadata:
      labels:
        app: pt-tax-enrichment
        group: property
    spec:
      containers:
      - name: pt-tax-enrichment
        image: {{conf['pt-tax-enrichment']['images'][0]}}
        ports:
        - containerPort: 8080
        env:
        - name: SERVER_PORT
          value: "8080"
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            configMapKeyRef:
              name: egov-config
              key: db-url
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: db
              key: username
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db
              key: password
        - name: EGOV_PROPERTYTAX_CREATE_DEMAND
          value: property-create-tax-generated
        - name: EGOV_SERVICES_BILLING_SERVICE_HOSTNAME
          value: "{{conf['egov-service-host']['billing-service']}}"
        - name: EGOV_SERVICES_PT_CALCULATOR_HOSTNAME
          value: "{{conf['egov-service-host']['pt-calculator']}}"
        - name: EGOV_PROPERTYTAX_CREATE_TAX_CALCULATED
          value: property-create-tax-calculated
        - name: EGOV_PROPERTYTAX_CREATE_WORKFLOW_STARTED
          value: property-create-workflow-started
        - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
          valueFrom:
            configMapKeyRef:
              name: egov-config
              key: kafka-brokers
        - name: APP_TIMEZONE
          valueFrom:
            configMapKeyRef:
              name: egov-config
              key: timezone
        - name: JAVA_OPTS
          value: "{{conf['pt-tax-enrichment']['heap'] or '-Xmx64m -Xms64m'}}"
        - name: SPRING_JPA_SHOW_SQL
          value: "{{conf['egov-config']['spring-jpa-show-sql']}}"
        resources:
          requests:
            memory: "64Mi"
          limits:
            memory: "{{ conf['pt-tax-enrichment']['memory_limits'] or "256Mi"}}"
