---
- name: Install etcd
  yum: name=etcd state=present
  become: true

- name: Update etcd conf
  become: true
  copy: src=etcd.conf dest=/etc/etcd/etcd.conf mode=0644

- name: restart and enable etcd services
  systemd: name=etcd daemon_reload=yes state=restarted enabled=yes
  become: true

- name: Check for kubernetes network config
  command: etcdctl ls {{ kubernetes_network_config_key }}
  register: network_config
  ignore_errors: yes

- name: Create kubernetes network config
  command: etcdctl mk {{ kubernetes_network_config_key }} '{"Network":"{{ kubernetes_pod_network }}"}'
  when: network_config.rc != 0
