apiVersion: v1
kind: Service
metadata:
  name: employee
  namespace: egov
  labels:
    app: employee
    group: web
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: employee
    group: web
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: employee
  namespace: egov
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  replicas: {{conf['employee']['replicas']}}
  template:
    metadata:
      labels:
        app: employee
        group: web
    spec:
      containers:
      - name: employee
        image: {{conf['employee']['images'][0]}}
        env:
        - name: REACT_APP_WS_FINANCIALINDICATORS
          value: {{conf['employee']['dashboard-url']}}
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /employee/
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
        resources:
          requests:
            memory: "128Mi"
          limits:
            memory: "{{ conf['employee']['memory_limits'] or "128Mi"}}"
