apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: logrotate
  namespace: logging
  labels:
    k8s-app: logrotate
spec:
  template:
    metadata:
      labels:
        k8s-app: logrotate
    spec:
      containers:
      - name: logrotate
        image: {{conf['logrotate']['images'][0]}}
        securityContext:
          privileged: true
        volumeMounts:
         - name: containers
           mountPath: /var/lib/docker/containers
         - name: varlog
           mountPath: /var/log/
        env:
        - name: LOGS_DIRECTORIES
          value: "/var/lib/docker/containers /var/log"
        # - name: LOGROTATE_INTERVAL
        #   value: {{conf['logrotate']['logrotate-interval']}}
        - name: LOGROTATE_COMPRESSION
          value: compress
        - name: LOGROTATE_CRONSCHEDULE
          value: "1 1 0 * * *"
        - name: LOGROTATE_LOGFILE
          value: "/var/log/logrotatecron.status"
      volumes:
         - hostPath:
             path: /var/lib/docker/containers
           name: containers
         - hostPath:
             path: /var/log/
           name: varlog
