apiVersion: v1
kind: LimitRange
metadata:
  name: egov-memory-limit
  namespace: egov
spec:
  limits:
    - max:
        memory: 1024Mi
      min:
        memory: 32Mi
      type: Container
---
apiVersion: v1
kind: LimitRange
metadata:
  name: egov-memory-limit
  namespace: es-cluster
spec:
  limits:
    - max:
        memory: 2048Mi
      min:
        memory: 32Mi
      type: Container
