apiVersion: v1
kind: Namespace
metadata:
  name: backbone
---
apiVersion: v1
kind: Namespace
metadata:
  name: es-cluster
---
apiVersion: v1
kind: Namespace
metadata:
  name: egov
---
apiVersion: v1
kind: Namespace
metadata:
  name: logging
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
apiVersion: v1
kind: Namespace
metadata:
  name: playground
---
apiVersion: v1
kind: Namespace
metadata:
  name: infra
---
apiVersion: v1
kind: Namespace
metadata:
  name: swmpoc
