apiVersion: v1
kind: Secret
metadata:
  name: egov-notification-sms
  namespace: egov
type: Opaque
data:
  username: {{conf['egov-notification-sms-secret']['username'] | decrypt}}
  password: {{conf['egov-notification-sms-secret']['password'] | decrypt}}
---
apiVersion: v1
kind: Secret
metadata:
  name: db
  namespace: egov
type: Opaque
data:
  username: {{conf['db-secret']['username'] | decrypt}}
  password: {{conf['db-secret']['password'] | decrypt}}
  flyway-username: {{conf['db-secret']['username'] | decrypt}}
  flyway-password: {{conf['db-secret']['password'] | decrypt}}
{% if conf['egov-docker-registry-secret'] %}
---
apiVersion: v1
data:
  .dockercfg: {{conf['egov-docker-registry-secret']['dockercfg'] | decrypt}}
kind: Secret
metadata:
  name: regsecret
  namespace: egov
type: kubernetes.io/dockercfg
# --- 
# apiVersion: v1
# data:
#   .dockercfg: {{conf['egov-docker-registry-secret']['allvydockercfg'] | decrypt}}
# kind: Secret
# metadata:
#   name: allvyregsecret
#   namespace: egov
# type: kubernetes.io/dockercfg
{% endif %}
{% if conf['es-alerts'] %}
---
apiVersion: v1
kind: Secret
metadata:
  name: slack
  namespace: monitoring
type: Opaque
data:
  slack-url: {{conf['es-alerts']['slack-url'] | decrypt}}
{% endif %}
{% if conf['cloudwatch-push-mem-metrics']%}
---
apiVersion: v1
kind: Secret
metadata:
  name: aws-config
  namespace: monitoring
type: Opaque
data:
  aws-access-key-id: "{{conf['cloudwatch-push-mem-metrics']['aws_access_key_id'] | decrypt}}"
  aws-secret-access-key: "{{conf['cloudwatch-push-mem-metrics']['aws_secret_access_key'] | decrypt}}"
  aws-availability-zone: "{{conf['cloudwatch-push-mem-metrics']['aws_availability_zone'] | decrypt}}"
  arn: "{{conf['cloudwatch-push-mem-metrics']['arn'] | decrypt}}"
{% endif %}
{% if conf['verdaccio']%}
---
apiVersion: v1
kind: Secret
metadata:
  name: verdaccio-htpassword
  namespace: backbone
type: Opaque
data:
  verdaccio-htpassword: "{{conf['verdaccio']['htpassword'] | decrypt}}"
{% endif %}
{% if conf['egov-mdms-create']%}
---
apiVersion: v1
kind: Secret
metadata:
  name: egov-mdms-create
  namespace: egov
type: Opaque
data:
  egov-github-pass: "{{conf['egov-mdms-create']['egov-github-pass'] | decrypt}}"
{% endif %}

{% if conf['egov-wordpress-portal']%}
---
apiVersion: v1
kind: Secret
metadata:
  name: egov-wordpress-portal-db
  namespace: infra
type: Opaque
data:
  username: "{{conf['egov-wordpress-portal']['db-username'] | decrypt}}"
  password: "{{conf['egov-wordpress-portal']['db-password'] | decrypt}}"
{% endif %}

{% if conf['egov-integration']%}
---
apiVersion: v1
kind: Secret
metadata:
  name: egov-integration
  namespace: egov
type: Opaque
data:
  username: "{{conf['egov-integration']['innowave-api-auth-username'] | decrypt}}"
  password: "{{conf['egov-integration']['innowave-api-auth-password'] | decrypt}}"
  token: "{{conf['egov-integration']['innowave-api-auth-password-basic-token'] | decrypt}}"
{% endif %}

{% if conf['egov-filestore']['aws']%}
---
apiVersion: v1
kind: Secret
metadata:
  name: egov-filestore
  namespace: egov
type: Opaque
data:
  awskey: "{{conf['egov-filestore']['aws']['aws-key'] | decrypt}}"
  awssecretkey: "{{conf['egov-filestore']['aws']['aws-secret-key'] | decrypt}}"
{% endif %}

{% if conf['egov-location']['gmaps']%}
---
apiVersion: v1
kind: Secret
metadata:
  name: egov-location
  namespace: egov
type: Opaque
data:
  gmapskey: "{{conf['egov-location']['gmaps']['api-key'] | decrypt}}"
{% endif %}

{% if conf['egov-pg-service']%}
---
apiVersion: v1
kind: Secret
metadata:
  name: egov-pg-service
  namespace: egov
type: Opaque
data:
  axismerchantid: "{{conf['egov-pg-service']['axis-merchant-id'] | decrypt}}"
  axismerchantsecret: "{{conf['egov-pg-service']['axis-merchant-secret-key'] | decrypt}}"
  axismerchantuser: "{{conf['egov-pg-service']['axis-merchant-user'] | decrypt}}"
  axismerchantpwd: "{{conf['egov-pg-service']['axis-merchant-pwd'] | decrypt}}"
  axismerchantaccesscode: "{{conf['egov-pg-service']['axis-merchant-access-code'] | decrypt}}"
  paytmmerchantid: "{{conf['egov-pg-service']['paytm-merchant-id'] | decrypt}}"
  paytmmerchantsecret: "{{conf['egov-pg-service']['paytm-merchant-secret-key'] | decrypt}}"
  phonepemerchantid: "{{conf['egov-pg-service']['phonepe-merchant-id'] | decrypt}}"
  phonepemerchantsecret: "{{conf['egov-pg-service']['phonepe-merchant-secret-key'] | decrypt}}"

{% endif %}

{% if conf['secor']%}
---
apiVersion: v1
kind: Secret
metadata:
  name: aws-secor-config
  namespace: backbone
type: Opaque
data:
  aws-access-key: "{{conf['secor']['aws_access_key'] | decrypt}}"
  aws-secret-key: "{{conf['secor']['aws_secret_key'] | decrypt}}"
  aws-region: "{{conf['secor']['aws_region'] | decrypt}}"
{% endif %}

{% if conf['rainmaker-custom-service']%}
{% if conf['rainmaker-custom-service']['egov-bnd-api-key']%}
---
apiVersion: v1
kind: Secret
metadata:
  name: rainmaker-custom-service
  namespace: egov
type: Opaque
data:
  egov-bnd-api-key: "{{conf['rainmaker-custom-service']['egov-bnd-api-key'] | decrypt}}"
  egov-bnd-encryption-key: "{{conf['rainmaker-custom-service']['egov-bnd-encryption-key'] | decrypt}}"
{% endif %}
{% endif %}
{% if conf['pgadmin-config']%}
---
apiVersion: v1
kind: Secret
metadata:
  name: pgadmin
  namespace: playground
type: Opaque
data:
  admin-email: "{{conf['pgadmin-config']['admin-email'] | decrypt}}"
  admin-password: "{{conf['pgadmin-config']['admin-password'] | decrypt}}"
  read-email: "{{conf['pgadmin-config']['read-email'] | decrypt}}"
  read-password: "{{conf['pgadmin-config']['read-password'] | decrypt}}"
{% endif %}
{% if conf['egov-notification-mail']%}
---
apiVersion: v1
data:
  mailsenderpassword: "{{conf['egov-notification-mail']['password'] | decrypt}}"
kind: Secret
metadata:
  name: egov-notification-mail
  namespace: egov
type: Opaque
{% endif %}
