apiVersion: v1
kind: Service
metadata:
  name: swm-services
  namespace: egov
  labels:
    app: swm-services
    group: swm
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: swm-services
    group: swm
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: swm-services
  namespace: egov
spec:
  replicas: {{conf['swm-services']['replicas']}}
  template:
    metadata:
      labels:
        app: swm-services
        group: swm
      annotations:
        pod.beta.kubernetes.io/init-containers: '[
          {
            "name": "swm-services-db-migration",
            "image": "{{conf["swm-services"]["db_migration_image"]}}",
            "env": [
              {"name": "DB_URL", "valueFrom": {"configMapKeyRef": {"name": "egov-config", "key": "db-url"}}},
              {"name": "SCHEMA_TABLE", "value": "swm_services_schema"},
              {"name": "FLYWAY_USER", "valueFrom": {"secretKeyRef": {"name": "db", "key": "flyway-username"}}},
              {"name": "FLYWAY_PASSWORD", "valueFrom": {"secretKeyRef": {"name": "db", "key": "flyway-password"}}},
              {"name": "FLYWAY_LOCATIONS", "valueFrom": {"configMapKeyRef": {"name": "egov-config", "key": "flyway-locations"}}}
            ],
            "imagePullPolicy": "IfNotPresent"
          }
        ]'
    spec:
      containers:
      - name: swm-services
        image: {{conf['swm-services']['images'][0]}}
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            configMapKeyRef:
              name: egov-config
              key: db-url
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: db
              key: username
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db
              key: password
        - name: SPRING_KAFKA_PRODUCER_KEY_SERIALIZER
          value: org.apache.kafka.common.serialization.StringSerializer
        - name: SPRING_KAFKA_PRODUCER_VALUE_SERIALIZER
          value: org.springframework.kafka.support.serializer.JsonSerializer
        - name: EGOV_SWM_VEHICLEFUELLINGDETAILS_SAVE_TOPIC
          value: swm-vehiclefuellingdetails-save-topic
        - name: EGOV_SWM_VEHICLEFUELLINGDETAILS_UPDATE_TOPIC
          value: swm-vehiclefuellingdetails-update-topic
        - name: EGOV_SWM_VEHICLEFUELLINGDETAILS_INDEXER_TOPIC
          value: swm-vehiclefuellingdetails-indexer-topic
        - name: FLYWAY_ENABLED
          value: "false"
        - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
          valueFrom:
            configMapKeyRef:
              name: egov-config
              key: kafka-brokers
        - name: APP_TIMEZONE
          valueFrom:
            configMapKeyRef:
              name: egov-config
              key: timezone
        - name: JAVA_OPTS
          value: "{{conf['swm-services']['heap'] or '-Xmx256m -Xms256m'}}"
{% if conf['egov-config']['serializers-timezone-in-ist'] %}
        - name: SPRING_KAFKA_CONSUMER_VALUE_DESERIALIZER
          value: org.egov.tracer.kafka.deserializer.ISTTimeZoneHashMapDeserializer
        - name: SPRING_KAFKA_PRODUCER_VALUE_SERIALIZER
          value: org.egov.tracer.kafka.serializer.ISTTimeZoneJsonSerializer
{% endif %}
        - name: SERVER_PORT
          value: "8080"
        - name: EGOV_SERVICES_EGOV_IDGEN_HOSTNAME
          value: "{{conf['egov-service-host']['egov-idgen']}}"
        - name: EGOV_SERVICES_EGOV_MDMS_HOSTNAME
          value: "{{conf['egov-service-host']['egov-mdms-service']}}"
        - name: EGOV_SERVICES_HR_MASTERS_HOSTNAME
          value: "{{conf['egov-service-host']['hr-masters']}}"
        - name: EGOV_SERVICES_HR_EMPLOYEE_HOSTNAME
          value: "{{conf['egov-service-host']['hr-employee']}}"
        - name: EGOV_SERVICES_BOUNDARY_HOST
          value: "{{conf['egov-service-host']['egov-location']}}"
        - name: EGOV_SERVICES_EGOV_ASSET_HOSTNAME
          value: "{{conf['egov-service-host']['asset-services-maha']}}"
        - name: LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_JDBC_CORE_JDBCTEMPLATE
          value: "{{conf['egov-config']['logging-level-jdbc']}}"
        resources:
          requests:
            memory: "256Mi"
          limits:
            memory: "{{ conf['swm-services']['memory_limits'] or "512Mi"}}"
