apiVersion: v1
kind: Service
metadata:
  name: wcms-notification
  namespace: egov
  labels:
    app: wcms-notification
    group: wcms
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: wcms-notification
    group: wcms
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: wcms-notification
  namespace: egov
spec:
  replicas: {{conf['wcms-notification']['replicas']}}
  template:
    metadata:
      labels:
        app: wcms-notification
        group: wcms
    spec:
      containers:
      - name: wcms-notification
        image: {{conf['wcms-notification']['images'][0]}}
        ports:
        - containerPort: 8080
        env:
        - name: KAFKA_TOPICS_NOTIFICATION_CONNECTION_CREATE_NAME
          value: egov.wcms.newconnection-create
        - name: KAFKA_TOPICS_NOTIFICATION_CONNECTION_UPDATE_NAME
          value: egov.wcms.newconnection-update
        - name: KAFKA_TOPICS_NOTIFICATION_SMS_NAME
          value: egov.core.notification.sms
        - name: KAFKA_TOPICS_NOTIFICATION_SMS_ID
          value: notification.sms
        - name: KAFKA_TOPICS_NOTIFICATION_SMS_KEY
          value: sms-notification
        - name: EGOV_SERVICES_TENANT_HOST
          value: "{{conf['egov-service-host']['tenant']}}"
        - name: SPRING_KAFKA_CONSUMER_GROUP_ID
          value: wcms-notification-group
        - name: SPRING_KAFKA_CONSUMER_KEY_DESERIALIZER
          value: org.apache.kafka.common.serialization.StringDeserializer
        - name: SPRING_KAFKA_PRODUCER_KEY_SERIALIZER
          value: org.apache.kafka.common.serialization.StringSerializer
{% if conf['egov-config']['serializers-timezone-in-ist'] %}
        - name: SPRING_KAFKA_CONSUMER_VALUE_DESERIALIZER
          value: org.egov.tracer.kafka.deserializer.ISTTimeZoneHashMapDeserializer
        - name: SPRING_KAFKA_PRODUCER_VALUE_SERIALIZER
          value: org.egov.tracer.kafka.serializer.ISTTimeZoneJsonSerializer
{% endif %}
        - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
          valueFrom:
            configMapKeyRef:
              name: egov-config
              key: kafka-brokers
        - name: APP_TIMEZONE
          valueFrom:
            configMapKeyRef:
              name: egov-config
              key: timezone
        - name: JAVA_OPTS
          value: "{{conf['wcms-notification']['heap'] or '-Xmx64m -Xms64m'}}"
        - name: SPRING_JPA_SHOW_SQL
          value: "{{conf['egov-config']['spring-jpa-show-sql']}}"
        - name: SERVER_PORT
          value: "8080"
        resources:
          requests:
            memory: "64Mi"
          limits:
            memory: "{{ conf['wcms-notification']['memory_limits'] or "256Mi"}}"
