apiVersion: v1
kind: Service
metadata:
  name: wcms-connection
  namespace: egov
  labels:
    app: wcms-connection
    group: wcms
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: wcms-connection
    group: wcms
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: wcms-connection
  namespace: egov
spec:
  replicas: {{conf['wcms-connection']['replicas']}}
  template:
    metadata:
      labels:
        app: wcms-connection
        group: wcms
      annotations:
        pod.beta.kubernetes.io/init-containers: '[
          {
            "name": "wcms-connection-db-migration",
            "image": "{{conf["wcms-connection"]["db_migration_image"]}}",
            "env": [
              {"name": "DB_URL", "valueFrom": {"configMapKeyRef": {"name": "egov-config", "key": "db-url"}}},
              {"name": "SCHEMA_TABLE", "value": "wcms_master_schema_version"},
              {"name": "FLYWAY_USER", "valueFrom": {"secretKeyRef": {"name": "db", "key": "flyway-username"}}},
              {"name": "FLYWAY_PASSWORD", "valueFrom": {"secretKeyRef": {"name": "db", "key": "flyway-password"}}},
              {"name": "FLYWAY_LOCATIONS", "valueFrom": {"configMapKeyRef": {"name": "egov-config", "key": "flyway-locations"}}}
            ],
            "imagePullPolicy": "IfNotPresent"
          }
        ]'
    spec:
      containers:
      - name: wcms-connection
        image: {{conf['wcms-connection']['images'][0]}}
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            configMapKeyRef:
              name: egov-config
              key: db-url
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: db
              key: username
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db
              key: password
        - name: FLYWAY_URL
          valueFrom:
            configMapKeyRef:
              name: egov-config
              key: db-url
        - name: SPRING_DATASOURCE_TOMCAT_INITIAL_SIZE
          valueFrom:
            configMapKeyRef:
              name: egov-config
              key: spring-datasource-tomcat-initialSize
        - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
          valueFrom:
            configMapKeyRef:
              name: egov-config
              key: kafka-brokers
        - name: SERVER_PORT
          value: "8080"
        - name: KAFKA_TOPICS_NEWCONNECTION_CREATE_NAME
          value: egov.wcms.newconnection-create
        - name: KAFKA_TOPICS_NEWCONNECTION_UPDATE_NAME
          value: egov.wcms.newconnection-update
        - name: KAFKA_TOPICS_UPDATE_WCMS
          value: wcms-update-db
        - name: KAFKA_TOPICS_SAVE_WCMS
          value: wcms-save-db
        - name: KAFKA_TOPICS_START_WORKFLOW
          value: wcms-workflow-start
        - name: KAFKA_TOPICS_UPDATE_WORKFLOW
          value: wcms-workflow-update
        - name: KAFKA_TOPICS_LEGACYCONNECTION_CREATE_NAME
          value: egov.wcms.legacyconnection-create
        - name: EGOV_SERVICES_WORKFLOW_SERVICE_HOSTNAME
          value: "{{conf['egov-service-host']['egov-common-workflows']}}"
        - name: KAFKA_CONSUMER_CONFIG_GROUP_ID
          value: wcms-connection-group
        - name: FLYWAY_ENABLED
          value: "false"
        - name: SPRING_JPA_SHOW_SQL
          value: "{{conf['egov-config']['spring-jpa-show-sql']}}"
        - name: EGOV_SERVICES_EGOV_USER_HOSTNAME
          value: "{{conf['egov-service-host']['egov-user']}}"
        - name: EGOV_SERVICES_TENANT_HOST
          value: "{{conf['egov-service-host']['tenant']}}"
        - name: EGOV_SERVICES_WCMSMASTERS_LOCAL_HOSTNAME
          value: "{{conf['egov-service-host']['wcms-masters']}}"
        - name: JAVA_OPTS
          value: "{{conf['wcms-masters']['heap'] or '-Xmx64m -Xms64m'}}"
{% if conf['egov-config']['serializers-timezone-in-ist'] %}
        - name: SPRING_KAFKA_CONSUMER_VALUE_DESERIALIZER
          value: org.egov.tracer.kafka.deserializer.ISTTimeZoneHashMapDeserializer
        - name: SPRING_KAFKA_PRODUCER_VALUE_SERIALIZER
          value: org.egov.tracer.kafka.serializer.ISTTimeZoneJsonSerializer
{% endif %}
        resources:
          requests:
            memory: "64Mi"
          limits:
            memory: "{{ conf['wcms-connection']['memory_limits'] or "256Mi"}}"
