apiVersion: v1
kind: Service
metadata:
  name: nginx-gw
  namespace: egov
  labels:
    app: nginx-gw
    group: gateway
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: nginx-gw
    group: gateway
  type: "{{conf['nginx-gw']['service_type']}}"
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-gw
  namespace: egov
spec:
  replicas: {{conf['nginx-gw']['replicas']}}
  template:
    metadata:
      labels:
        app: nginx-gw
        group: gateway
    spec:
      containers:
      - name: nginx-gw
        image: {{conf['nginx-gw']['images'][0]}}
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "32Mi"
          limits:
            memory: "{{ conf['nginx-gw']['memory_limits'] or "128Mi"}}"
      - name: dnsmasq
        image: {{conf['nginx-gw']['images'][1]}}
        args:
          - --listen
          - "127.0.0.1:53"
          - --default-resolver
          - --append-search-domains
          - --hostsfile=/etc/hosts
          - --verbose
        resources:
          requests:
            memory: "32Mi"
          limits:
            memory: "64Mi"
