apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pgr-employee-enrichment
  namespace: egov
spec:
  replicas: {{conf['pgr-employee-enrichment']['replicas']}}
  template:
    metadata:
      labels:
        app: pgr-employee-enrichment
        group: pgr
    spec:
      containers:
      - name: pgr-employee-enrichment
        image: {{conf['pgr-employee-enrichment']['images'][0]}}
        env:
        - name: EGOV_SERVICES_CROSSHIERARCHY_SERVICE_HOST
          value: "{{conf['egov-service-host']['location']}}"
        - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
          valueFrom:
            configMapKeyRef:
              name: egov-config
              key: kafka-brokers
        - name: EGOV_SERVICES_WORKFLOW_HOSTNAME
          value: "{{conf['egov-service-host']['egov-workflow']}}"
        - name: KAFKA_TOPICS_PGR_LOCATIONPOPULATED_NAME
          value: egov.pgr.locationupdated
        - name: KAFKA_TOPICS_PGR_LOCATIONPOPULATED_ID
          value: egov.pgr.locationupdated
        - name: KAFKA_TOPICS_PGR_LOCATIONPOPULATED_GROUP
          value: egov.pgr.locationupdated
        - name: KAFKA_TOPICS_PGR_EMPLOYEE_ENRICHED_NAME
          value: egov.pgr.workflowupdated
        - name: EGOV_SERVICES_PGR_HOST
          value: "{{conf['egov-service-host']['pgr-rest']}}"
        - name: EGOV_SERVICES_POSITION_HOST
          value: "{{conf['egov-service-host']['hr-masters']}}"
        - name: FLYWAY_ENABLED
          value: "false"
        - name: EGOV_SERVICES_COMMON_WORKFLOW_HOSTNAME
          value: "{{conf['egov-service-host']['egov-common-workflows']}}"
        - name: APP_TIMEZONE
          valueFrom:
            configMapKeyRef:
              name: egov-config
              key: timezone
{% if conf['egov-config']['serializers-timezone-in-ist'] %}
        - name: SPRING_KAFKA_CONSUMER_VALUE_DESERIALIZER
          value: org.egov.tracer.kafka.deserializer.ISTTimeZoneHashMapDeserializer
        - name: SPRING_KAFKA_PRODUCER_VALUE_SERIALIZER
          value: org.egov.tracer.kafka.serializer.ISTTimeZoneJsonSerializer
{% endif %}
        resources:
          requests:
            memory: "64Mi"
          limits:
            memory: "{{ conf['pgr-employee-enrichment']['memory_limits'] or "256Mi"}}"
