apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pgr-search-indexer
  namespace: egov
spec:
  replicas: {{conf['pgr-search-indexer']['replicas']}}
  template:
    metadata:
      labels:
        app: pgr-search-indexer
        group: pgr
    spec:
      containers:
      - name: pgr-search-indexer
        image: {{conf['pgr-search-indexer']['images'][0]}}
        env:
        - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
          valueFrom:
            configMapKeyRef:
              name: egov-config
              key: kafka-brokers
        - name: EGOV_SERVICES_HREMPLOYEE_HOST
          value: "{{conf['egov-service-host']['hr-employee']}}"
        - name: EGOV_SERVICES_BOUNDARY_HOST
          value: "{{conf['egov-service-host']['egov-location']}}"
        - name: EGOV_SERVICES_PGRREST_HOST
          value: "{{conf['egov-service-host']['pgr-rest']}}"
        - name: EGOV_SERVICES_TENANT_HOST
          value: "{{conf['egov-service-host']['tenant']}}"
        - name: EGOV_SERVICES_COMMONMASTERS_HOST
          value: "{{conf['egov-service-host']['egov-common-masters']}}"
        - name: EGOV_SERVICES_ESINDEXER_HOST
          valueFrom:
            configMapKeyRef:
              name: egov-config
              key: es-indexer-host
        - name: FLYWAY_ENABLED
          value: "false"
        - name: KAFKA_TOPICS_EGOV_INDEX_NAME
          value: egov.pgr.workflowupdated
        - name: APP_TIMEZONE
          valueFrom:
            configMapKeyRef:
              name: egov-config
              key: timezone
{% if conf['egov-config']['serializers-timezone-in-ist'] %}
        - name: SPRING_KAFKA_CONSUMER_VALUE_DESERIALIZER
          value: org.egov.tracer.kafka.deserializer.ISTTimeZoneHashMapDeserializer
        - name: SPRING_KAFKA_PRODUCER_VALUE_SERIALIZER
          value: org.egov.tracer.kafka.serializer.ISTTimeZoneJsonSerializer
{% endif %}
        resources:
          requests:
            memory: "64Mi"
          limits:
            memory: "{{ conf['pgr-search-indexer']['memory_limits'] or "256Mi"}}"
