apiVersion: v1
kind: Service
metadata:
  name: asset-services-maha
  namespace: egov
  labels:
    app: asset-services-maha
    group: asset
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: asset-services-maha
    group: asset
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: asset-services-maha
  namespace: egov
spec:
  replicas: {{conf['asset-services-maha']['replicas']}}
  template:
    metadata:
      labels:
        app: asset-services-maha
        group: asset
      annotations:
        pod.beta.kubernetes.io/init-containers: '[
          {
            "name": "asset-services-maha-db-migration",
            "image": "{{conf["asset-services-maha"]["db_migration_image"]}}",
            "env": [
              {"name": "DB_URL", "valueFrom": {"configMapKeyRef": {"name": "egov-config", "key": "db-url"}}},
              {"name": "SCHEMA_TABLE", "value": "asset_services_maha_schema"},
              {"name": "FLYWAY_USER", "valueFrom": {"secretKeyRef": {"name": "db", "key": "flyway-username"}}},
              {"name": "FLYWAY_PASSWORD", "valueFrom": {"secretKeyRef": {"name": "db", "key": "flyway-password"}}},
              {"name": "FLYWAY_LOCATIONS", "valueFrom": {"configMapKeyRef": {"name": "egov-config", "key": "flyway-locations"}}}
            ],
            "imagePullPolicy": "IfNotPresent"
          }
        ]'
    spec:
      containers:
      - name: asset-services-maha
        image: {{conf['asset-services-maha']['images'][0]}}
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            configMapKeyRef:
              name: egov-config
              key: db-url
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: db
              key: username
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db
              key: password
        - name: KAFKA_TOPICS_ASSET_ID
          value: asset
        - name: SPRING_KAFKA_CONSUMER_KEY_DESERIALIZER
          value: org.apache.kafka.common.serialization.StringDeserializer
        - name: SPRING_KAFKA_CONSUMER_GROUP_ID
          value: asset-group
        - name: SPRING_KAFKA_PRODUCER_KEY_SERIALIZER
          value: org.apache.kafka.common.serialization.StringSerializer
{% if conf['egov-config']['serializers-timezone-in-ist'] %}
        - name: SPRING_KAFKA_CONSUMER_VALUE_DESERIALIZER
          value: org.egov.tracer.kafka.deserializer.ISTTimeZoneHashMapDeserializer
        - name: SPRING_KAFKA_PRODUCER_VALUE_SERIALIZER
          value: org.egov.tracer.kafka.serializer.ISTTimeZoneJsonSerializer
{% endif %}
        - name: KAFKA_CONSUMER_CONFIG_GROUP_ID
          value: asset-group
        - name: EGOV_SERVICES_EGF_MASTERS_HOST
          value: "{{conf['egov-service-host']['egf-masters']}}"
        - name: MDMS_SERVICE_HOST
          value: "{{conf['egov-service-host']['egov-mdms-service']}}"
        - name: FLYWAY_ENABLED
          value: "false"
        - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
          valueFrom:
            configMapKeyRef:
              name: egov-config
              key: kafka-brokers
        - name: APP_TIMEZONE
          valueFrom:
            configMapKeyRef:
              name: egov-config
              key: timezone
        - name: JAVA_OPTS
          value: "{{conf['asset-services-maha']['heap'] or '-Xmx64m -Xms64m'}}"
        - name: SERVER_PORT
          value: "8080"
        resources:
          requests:
            memory: "64Mi"
          limits:
            memory: "{{ conf['asset-services-maha']['memory_limits'] or "256Mi"}}"
