apiVersion: v1
kind: Service
metadata:
  name: works-workorder
  namespace: egov
  labels:
    app: works-workorder
    group: works
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: works-workorder
    group: works
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: works-workorder
  namespace: egov
spec:
  replicas: {{conf['works-workorder']['replicas']}}
  template:
    metadata:
      labels:
        app: works-workorder
        group: works
      annotations:
        pod.beta.kubernetes.io/init-containers: '[
          {
            "name": "works-workorder-db-migration",
            "image": "{{conf["works-workorder"]["db_migration_image"]}}",
            "env": [
              {"name": "DB_URL", "valueFrom": {"configMapKeyRef": {"name": "egov-config", "key": "db-url"}}},
              {"name": "SCHEMA_TABLE", "value": "works_workorder_schema"},
              {"name": "FLYWAY_USER", "valueFrom": {"secretKeyRef": {"name": "db", "key": "flyway-username"}}},
              {"name": "FLYWAY_PASSWORD", "valueFrom": {"secretKeyRef": {"name": "db", "key": "flyway-password"}}},
              {"name": "FLYWAY_LOCATIONS", "valueFrom": {"configMapKeyRef": {"name": "egov-config", "key": "flyway-locations"}}}
            ],
            "imagePullPolicy": "IfNotPresent"
          }
        ]'
    spec:
      containers:
      - name: works-workorder
        image: {{conf['works-workorder']['images'][0]}}
        ports:
        - containerPort: 8080
        env:
        - name: SERVER_CONTEXT_PATH
          value: /works-workorder/v1
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            configMapKeyRef:
              name: egov-config
              key: db-url
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: db
              key: username
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db
              key: password
        - name: WORKS_WORKORDER_HOST_URL
          value: "{{conf['egov-service-host']['works-workorder']}}"
        - name: SPRING_EMBEDDED_KAFKA_BROKERS
          value: embededkafkabroker
        - name: SPRING_KAFKA_CONSUMER_VALUE_DESERIALIZER
          value: org.egov.works.workorder.common.queue.HashMapDeserializer
        - name: SPRING_KAFKA_CONSUMER_KEY_DESERIALIZER
          value: org.apache.kafka.common.serialization.StringDeserializer
        - name: SPRING_KAFKA_CONSUMER_GROUP_ID
          value: works-workorder-group
        - name: SPRING_KAFKA_PRODUCER_KEY_SERIALIZER
          value: org.apache.kafka.common.serialization.StringSerializer
        - name: SPRING_KAFKA_PRODUCER_VALUE_SERIALIZER
          value: org.springframework.kafka.support.serializer.JsonSerializer
        - name: EGOV_SERVICES_EGOV_MDMS_SEARCHPATH
          value: egov-mdms-service/v1/_search
        - name: EGOV_SERVICES_EGOV_WORKS_SERVICES_HOSTNAME
          value: "{{conf['egov-service-host']['works-services']}}"
        - name: EGOV_IDGEN_HOSTNAME
          value:  "{{conf['egov-service-host']['egov-idgen']}}"
        - name: EGOV_WORKS_MASTERSHOST
          value: "{{conf['egov-service-host']['works-masters']}}"
        - name: EGOV_SERVICES_EGOV_WORKS_ESTIMATE_HOSTNAME
          value: "{{conf['egov-service-host']['works-estimate']}}"
        - name: EGOV_SERVICES_EGOV_MDMS_HOSTNAME
          value: "{{conf['egov-service-host']['egov-mdms-service']}}"
        - name: EGOV_SERVICES_HR_EMPLOYEE_HOSTNAME
          value: "{{conf['egov-service-host']['hr-employee']}}"
        - name: EGOV_SERVICES_EGOV_WORKS_MEASUREMENTBOOK_HOSTNAME
          value: "{{conf['egov-service-host']['works-measurementbook']}}"
        - name: EGOV_SERVICES_EGOV_WORKS_MEASUREMENTBOOK_SEARCHPATH
          value: /works-measurementbook/v1/contractorbills/_search
        - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
          valueFrom:
            configMapKeyRef:
              name: egov-config
              key: kafka-brokers
        - name: APP_TIMEZONE
          valueFrom:
            configMapKeyRef:
              name: egov-config
              key: timezone
        - name: JAVA_OPTS
          value: "{{conf['works-workorder']['heap'] or '-Xmx64m -Xms64m'}}"
        - name: SERVER_PORT
          value: "8080"
        - name: FLYWAY_ENABLED
          value: "false"
        resources:
          requests:
            memory: "64Mi"
          limits:
            memory : "{{ conf['works-workorder']['memory_limits'] or "256Mi"}}"
