apiVersion: v1
kind: Service
metadata:
  name: works-measurementbook
  namespace: egov
  labels:
    app: works-measurementbook
    group: works
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: works-measurementbook
    group: works
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: works-measurementbook
  namespace: egov
spec:
  replicas: {{conf['works-measurementbook']['replicas']}}
  template:
    metadata:
      labels:
        app: works-measurementbook
        group: works
      annotations:
        pod.beta.kubernetes.io/init-containers: '[
          {
            "name": "works-measurementbook-db-migration",
            "image": "{{conf["works-measurementbook"]["db_migration_image"]}}",
            "env": [
              {"name": "DB_URL", "valueFrom": {"configMapKeyRef": {"name": "egov-config", "key": "db-url"}}},
              {"name": "SCHEMA_TABLE", "value": "works_measurementbook_schema"},
              {"name": "FLYWAY_USER", "valueFrom": {"secretKeyRef": {"name": "db", "key": "flyway-username"}}},
              {"name": "FLYWAY_PASSWORD", "valueFrom": {"secretKeyRef": {"name": "db", "key": "flyway-password"}}},
              {"name": "FLYWAY_LOCATIONS", "valueFrom": {"configMapKeyRef": {"name": "egov-config", "key": "flyway-locations"}}}
            ],
            "imagePullPolicy": "IfNotPresent"
          }
        ]'
    spec:
      containers:
      - name: works-measurementbook
        image: {{conf['works-measurementbook']['images'][0]}}
        ports:
        - containerPort: 8080
        env:
        - name: SERVER_CONTEXT_PATH
          value: /works-measurementbook/v1
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            configMapKeyRef:
              name: egov-config
              key: db-url
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: db
              key: username
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db
              key: password
        - name: WORKS_WORKORDER_HOST_URL
          value: "{{conf['egov-service-host']['works-workorder']}}"
        - name: SPRING_EMBEDDED_KAFKA_BROKERS
          value: embededkafkabroker
        - name: SPRING_KAFKA_CONSUMER_VALUE_DESERIALIZER
          value: org.egov.works.measurementbook.common.queue.HashMapDeserializer
        - name: SPRING_KAFKA_CONSUMER_KEY_DESERIALIZER
          value: org.apache.kafka.common.serialization.StringDeserializer
        - name: SPRING_KAFKA_CONSUMER_GROUP_ID
          value: works-measurementbook-group
        - name: SPRING_KAFKA_PRODUCER_KEY_SERIALIZER
          value: org.apache.kafka.common.serialization.StringSerializer
        - name: SPRING_KAFKA_PRODUCER_VALUE_SERIALIZER
          value: org.springframework.kafka.support.serializer.JsonSerializer
        - name: EGOV_SERVICES_EGOV_MDMS_HOSTNAME
          value: "{{conf['egov-service-host']['egov-mdms-service']}}"
        - name: EGOV_SERVICES_EGOV_MDMS_SEARCHPATH
          value: egov-mdms-service/v1/_search
        - name: EGOV_SERVICES_EGOV_WORKS_ESTIMATE_HOSTNAME
          value: "{{conf['egov-service-host']['works-estimate']}}"
        - name: EGOV_IDGEN_HOSTNAME 
          value:  "{{conf['egov-service-host']['egov-idgen']}}"
        - name: EGOV_SERVICES_WORKORDER_HOSTNAME
          value: "{{conf['egov-service-host']['works-workorder']}}"
        - name: EGOV_SERVICES_EGF_BILL_HOSTNAME
          value: "{{conf['egov-service-host']['egf-bill']}}"
        - name: EGOV_SERVICES_EGF_BILLREGISTER_CREATEPATH
          value: /egf-bill/bills/_create
        - name: EGOV_SERVICES_EGF_BILLREGISTER_UPDATEPATH
          value: /egf-bill/bills/_update
        - name: EGOV_SERVICES_EGOV_OFFLINESTATUS_HOSTNAME
          value: "{{conf['egov-service-host']['works-services']}}"
        - name: EGOV_SERVICES_EGOV_OFFLINESTATUS_SEARCHPATH
          value: /works-services/v1/offlinestatuses/_search
        - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
          valueFrom:
            configMapKeyRef:
              name: egov-config
              key: kafka-brokers
        - name: APP_TIMEZONE
          valueFrom:
            configMapKeyRef:
              name: egov-config
              key: timezone
        - name: JAVA_OPTS
          value: "{{conf['works-measurementbook']['heap'] or '-Xmx64m -Xms64m'}}"
        - name: SERVER_PORT
          value: "8080"
        - name: FLYWAY_ENABLED
          value: "false"
        resources:
          requests:
            memory: "64Mi"
          limits:
            memory : "{{conf['works-measurementbook']['memory_limits'] or "256Mi"}}"