apiVersion: v1
kind: Service
metadata:
  name: works-qualitycontrol
  namespace: egov
  labels:
    app: works-qualitycontrol
    group: works
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: works-qualitycontrol
    group: works
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: works-qualitycontrol
  namespace: egov
spec:
  replicas: {{conf['works-qualitycontrol']['replicas']}}
  template:
    metadata:
      labels:
        app: works-qualitycontrol
        group: works
      annotations:
        pod.beta.kubernetes.io/init-containers: '[
          {
            "name": "works-qualitycontrol-db-migration",
            "image": "{{conf["works-qualitycontrol"]["db_migration_image"]}}",
            "env": [
              {"name": "DB_URL", "valueFrom": {"configMapKeyRef": {"name": "egov-config", "key": "db-url"}}},
              {"name": "SCHEMA_TABLE", "value": "works_qualitycontrol_schema"},
              {"name": "FLYWAY_USER", "valueFrom": {"secretKeyRef": {"name": "db", "key": "flyway-username"}}},
              {"name": "FLYWAY_PASSWORD", "valueFrom": {"secretKeyRef": {"name": "db", "key": "flyway-password"}}},
              {"name": "FLYWAY_LOCATIONS", "valueFrom": {"configMapKeyRef": {"name": "egov-config", "key": "flyway-locations"}}}
            ],
            "imagePullPolicy": "IfNotPresent"
          }
        ]'
    spec:
      containers:
      - name: works-qualitycontrol
        image: {{conf['works-qualitycontrol']['images'][0]}}
        ports:
        - containerPort: 8080
        env:
        - name: SERVER_CONTEXT_PATH
          value: /works-qualitycontrol/v1
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            configMapKeyRef:
              name: egov-config
              key: db-url
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: db
              key: username
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db
              key: password
        - name: SPRING_EMBEDDED_KAFKA_BROKERS
          value: embededkafkabroker
        - name: SPRING_KAFKA_CONSUMER_KEY_DESERIALIZER
          value: org.apache.kafka.common.serialization.StringDeserializer
        - name: SPRING_KAFKA_CONSUMER_GROUP_ID
          value: works-qualitycontrol-group
        - name: SPRING_KAFKA_PRODUCER_KEY_SERIALIZER
          value: org.apache.kafka.common.serialization.StringSerializer
{% if conf['egov-config']['serializers-timezone-in-ist'] %}
        - name: SPRING_KAFKA_CONSUMER_VALUE_DESERIALIZER
          value: org.egov.tracer.kafka.deserializer.ISTTimeZoneHashMapDeserializer
        - name: SPRING_KAFKA_PRODUCER_VALUE_SERIALIZER
          value: org.egov.tracer.kafka.serializer.ISTTimeZoneJsonSerializer
{% endif %}
        - name: EGOV_SERVICES_EGOV_WORKS_ESTIMATE_HOSTNAME
          value: "{{conf['egov-service-host']['works-estimate']}}"
        - name: EGOV_SERVICES_EGOV_WORKORDER_SERVICE_HOSTNAME
          value: "{{conf['egov-service-host']['works-workorder']}}"
        - name: EGOV_FILESTORE_HOSTNAME
          value: "{{conf['egov-service-host']['egov-filestore']}}"
        - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
          valueFrom:
            configMapKeyRef:
              name: egov-config
              key: kafka-brokers
        - name: APP_TIMEZONE
          valueFrom:
            configMapKeyRef:
              name: egov-config
              key: timezone
        - name: JAVA_OPTS
          value: "{{conf['works-qualitycontrol']['heap'] or '-Xmx64m -Xms64m'}}"
        - name: SPRING_JPA_SHOW_SQL
          value: "{{conf['egov-config']['spring-jpa-show-sql']}}"
        - name: SERVER_PORT
          value: "8080"
        - name: FLYWAY_ENABLED
          value: "false"
        resources:
          requests:
            memory: "64Mi"
          limits:
            memory : "{{conf['works-qualitycontrol']['memory_limits'] or "256Mi"}}"