apiVersion: v1
kind: Service
metadata:
  name: kafka-rest
  namespace: swmpoc
  labels:
    app: kafka-rest
spec:
  ports:
  - name: kafka-rest
    port: 8082
    protocol: TCP
    targetPort: 8082
  clusterIP: None
  selector:
    app: kafka-rest
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: kafka-rest
  namespace: swmpoc
spec:
  replicas: 1
  serviceName: "kafka-rest"
  template:
    metadata:
      labels:
        app: kafka-rest
    spec:
      containers:
      - name: kafka-rest
        image: confluentinc/cp-kafka-rest:latest
        env:
        - name: KAFKA_REST_HEAP_OPTS
          value: "-Xmx256M -Xms128M"
        # - name: KAFKA_BROKER_ID
        #   value: "1"
        - name: KAFKA_REST_ZOOKEEPER_CONNECT
          value:  zookeeper-0.zookeeper.swmpoc:22181
        - name: KAFKA_REST_BOOTSTRAP_SERVERS
          value:  "PLAINTEXT://kafka-0.kafka.swmpoc:19092"
        - name: KAFKA_REST_HOST_NAME
          value: kafka-rest-0.kafka-rest.swmpoc:8082
        # - name: KAFKA_REQUEST_TIMEOUT_MS
        #   value: "100000"
