apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: swmpoc
  labels:
    app: kafka
spec:
  ports:
  - name: kafka
    port: 19092
    protocol: TCP
    targetPort: 19092
  clusterIP: None
  selector:
    app: kafka
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: kafka
  namespace: swmpoc
spec:
  replicas: 1
  serviceName: "kafka"
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka
        image: confluentinc/cp-kafka:latest
        env:
        - name: KAFKA_HEAP_OPTS
          value: "-Xmx512M -Xms256M"
        - name: KAFKA_BROKER_ID
          value: "1"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value:  zookeeper-0.zookeeper.swmpoc:22181
        - name: KAFKA_ADVERTISED_LISTENERS
          value:  "PLAINTEXT://kafka-0.kafka.swmpoc:19092"
        - name: KAFKA_REQUEST_TIMEOUT_MS
          value: "100000"
