apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: swmpoc
  labels:
    app: zookeeper
spec:
  ports:
  - port: 22181
    name: client
    protocol: TCP
  - port: 22888
    name: server
    protocol: TCP
  - port: 23888
    name: leader-election
    protocol: TCP
  clusterIP: None
  selector:
    app: zookeeper
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: zookeeper
  namespace: swmpoc
spec:
  serviceName: "zookeeper"
  replicas: 1
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
      - name: zookeeper
        image: confluentinc/cp-zookeeper:latest
        ports:
        - containerPort: 22181
          name: client
        - containerPort: 22888
          name: server
        - containerPort: 23888
          name: leader-election
        env:
        - name: ZOOKEEPER_SERVER_ID
          value: "1"
        - name: ZOOKEEPER_CLIENT_PORT
          value:  "22181"
        - name: ZOOKEEPER_TICK_TIME
          value: "2000"
        - name: ZOOKEEPER_INIT_LIMIT
          value:  "5"
        - name: ZOOKEEPER_SYNC_LIMIT
          value:  "2"
        - name: ZOOKEEPER_SERVERS
          value:  zookeeper-0.zookeeper.swmpoc:22888:23888
