apiVersion: v1
kind: Service
metadata:
  name: tl-indexer
  namespace: egov
  labels:
    app: tl-indexer
    group: tradelicense
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: tl-indexer
    group: tradelicense
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tl-indexer
  namespace: egov
spec:
  replicas: {{conf['tl-indexer']['replicas']}}
  template:
    metadata:
      labels:
        app: tl-indexer
        group: tradelicense
    spec:
      containers:
      - name: tl-indexer
        image: {{conf['tl-indexer']['images'][0]}}
        ports:
        - containerPort: 8080
        env:
        - name: CONSUMER_GROUP
          value: Indexer
        - name: SPRING_KAFKA_CONSUMER_KEY_DESERIALIZER
          value: org.apache.kafka.common.serialization.StringDeserializer
        - name: SPRING_KAFKA_CONSUMER_GROUP_ID
          value: pt-indexer-persist
        - name: SPRING_KAFKA_PRODUCER_KEY_SERIALIZER
          value: org.apache.kafka.common.serialization.StringSerializer
{% if conf['egov-config']['serializers-timezone-in-ist'] %}
        - name: SPRING_KAFKA_CONSUMER_VALUE_DESERIALIZER
          value: org.egov.tracer.kafka.deserializer.ISTTimeZoneHashMapDeserializer
        - name: SPRING_KAFKA_PRODUCER_VALUE_SERIALIZER
          value: org.egov.tracer.kafka.serializer.ISTTimeZoneJsonSerializer
{% endif %}
        - name: EGOV_SERVICES_TL_SERVICES_CREATE_LEGACY_TRADELICENSE_VALIDATED
          value: create-legacy-tradelicense-validated
        - name: ES_HOST
          valueFrom:
            configMapKeyRef:
              name: egov-config
              key: es-host
        - name: ES_PORT
          value: "9200"
        - name: TRADELICENSE_ES_INDEX_NAME
          value: tradelicense
        - name: TRADELICENSE_ES_INDEX_TYPE
          value: tradelicense_type
        - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
          valueFrom:
            configMapKeyRef:
              name: egov-config
              key: kafka-brokers
        - name: APP_TIMEZONE
          valueFrom:
            configMapKeyRef:
              name: egov-config
              key: timezone
        - name: JAVA_OPTS
          value: "{{conf['tl-indexer']['heap'] or '-Xmx64m -Xms64m'}}"
        - name: SPRING_JPA_SHOW_SQL
          value: "{{conf['egov-config']['spring-jpa-show-sql']}}"
        - name: SERVER_PORT
          value: "8080"
        resources:
          requests:
            memory: "64Mi"
          limits:
            memory: "{{ conf['tl-indexer']['memory_limits'] or "256Mi"}}"
