apiVersion: v1
kind: Service
metadata:
  name: tl-masters
  namespace: egov
  labels:
    app: tl-masters
    group: tradelicense
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: tl-masters
    group: tradelicense
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tl-masters
  namespace: egov
spec:
  replicas: {{conf['tl-masters']['replicas']}}
  template:
    metadata:
      labels:
        app: tl-masters
        group: tradelicense
      annotations:
        pod.beta.kubernetes.io/init-containers: '[
          {
            "name": "tl-masters-db-migration",
            "image": "{{conf["tl-masters"]["db_migration_image"]}}",
            "env": [
              {"name": "DB_URL", "valueFrom": {"configMapKeyRef": {"name": "egov-config", "key": "db-url"}}},
              {"name": "SCHEMA_TABLE", "value": "tl_masters_schema"},
              {"name": "FLYWAY_USER", "valueFrom": {"secretKeyRef": {"name": "db", "key": "flyway-username"}}},
              {"name": "FLYWAY_PASSWORD", "valueFrom": {"secretKeyRef": {"name": "db", "key": "flyway-password"}}},
              {"name": "FLYWAY_LOCATIONS", "valueFrom": {"configMapKeyRef": {"name": "egov-config", "key": "flyway-locations"}}}
            ],
            "imagePullPolicy": "IfNotPresent"
          }
        ]'
    spec:
      containers:
      - name: tl-masters
        image: {{conf['tl-masters']['images'][0]}}
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            configMapKeyRef:
              name: egov-config
              key: db-url
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: db
              key: username
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db
              key: password
        - name: EGOV_SERVICES_EGF_MASTERS_HOSTNAME
          value: "{{conf['egov-service-host']['egf-masters']}}"
        - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
          valueFrom:
            configMapKeyRef:
              name: egov-config
              key: kafka-brokers
        - name: APP_TIMEZONE
          valueFrom:
            configMapKeyRef:
              name: egov-config
              key: timezone
        - name: JAVA_OPTS
          value: "{{conf['tl-masters']['heap'] or '-Xmx64m -Xms64m'}}"
        - name: SPRING_JPA_SHOW_SQL
          value: "{{conf['egov-config']['spring-jpa-show-sql']}}"
        - name: SERVER_PORT
          value: "8080"
        - name: FLYWAY_ENABLED
          value: "false"
        resources:
          requests:
            memory: "64Mi"
          limits:
            memory: "{{ conf['tl-masters']['memory_limits'] or "256Mi"}}"
