apiVersion: v1
kind: Service
metadata:
  name: tl-notification
  namespace: egov
  labels:
    app: tl-notification
    group: tradelicense
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: tl-notification
    group: tradelicense
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tl-notification
  namespace: egov
spec:
  replicas: {{conf['tl-notification']['replicas']}}
  template:
    metadata:
      labels:
        app: tl-notification
        group: tradelicense
    spec:
      containers:
      - name: tl-notification
        image: {{conf['tl-notification']['images'][0]}}
        ports:
        - containerPort: 8080
        env:
        - name: EGOV_SERVICES_TENANT_SERVICE_HOSTNAME
          value: "{{conf['egov-service-host']['tenant']}}"
        - name: EGOV_SERVICES_TL_MASTERS_V1_HOSTNAME
          value: "{{conf['egov-service-host']['tl-masters']}}"
        - name: EGOV_SERVICES_TL_SERVICES_V1_HOSTNAME
          value: "{{conf['egov-service-host']['tl-services']}}"
        - name: EGOV_SERVICES_COLLECTIONS_COLLECTION_SERVICES_HOSTNAME
          value: "{{conf['egov-service-host']['collection-services']}}"
        - name: SPRING_KAFKA_CONSUMER_KEY_DESERIALIZER
          value: org.apache.kafka.common.serialization.StringDeserializer
        - name: SPRING_KAFKA_CONSUMER_GROUP_ID
          value: tl-notification
        - name: SPRING_KAFKA_PRODUCER_KEY_SERIALIZER
          value: org.apache.kafka.common.serialization.StringSerializer
{% if conf['egov-config']['serializers-timezone-in-ist'] %}
        - name: SPRING_KAFKA_CONSUMER_VALUE_DESERIALIZER
          value: org.egov.tracer.kafka.deserializer.ISTTimeZoneHashMapDeserializer
        - name: SPRING_KAFKA_PRODUCER_VALUE_SERIALIZER
          value: org.egov.tracer.kafka.serializer.ISTTimeZoneJsonSerializer
{% endif %}
        - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
          valueFrom:
            configMapKeyRef:
              name: egov-config
              key: kafka-brokers
        - name: APP_TIMEZONE
          valueFrom:
            configMapKeyRef:
              name: egov-config
              key: timezone
        - name: JAVA_OPTS
          value: "{{conf['tl-notification']['heap'] or '-Xmx64m -Xms64m'}}"
        - name: SPRING_JPA_SHOW_SQL
          value: "{{conf['egov-config']['spring-jpa-show-sql']}}"
        - name: SERVER_PORT
          value: "8080"
        - name: FLYWAY_ENABLED
          value: "false"
        - name: EGOV_SERVICES_FQDN_NAME
          value: "{{conf['egov-config']['egov-services-fqdn-name']}}"
        resources:
          requests:
            memory: "64Mi"
          limits:
            memory: "{{ conf['tl-notification']['memory_limits'] or "256Mi"}}"
