apiVersion: v1
kind: Service
metadata:
  name: lcms-workflow
  namespace: egov
  labels:
    app: lcms-workflow
    group: lcms
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: lcms-workflow
    group: lcms
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: lcms-workflow
  namespace: egov
spec:
  replicas: {{conf['lcms-workflow']['replicas']}}
  template:
    metadata:
      labels:
        app: lcms-workflow
        group: lcms
    spec:
      containers:
      - name: lcms-workflow
        image: {{conf['lcms-workflow']['images'][0]}}
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_KAFKA_CONSUMER_KEY_DESERIALIZER
          value: org.apache.kafka.common.serialization.StringDeserializer
        - name: SPRING_KAFKA_CONSUMER_GROUP_ID
          value: lcms-create
        - name: SPRING_KAFKA_PRODUCER_KEY_SERIALIZER
          value: org.apache.kafka.common.serialization.StringSerializer
{% if conf['egov-config']['serializers-timezone-in-ist'] %}
        - name: SPRING_KAFKA_CONSUMER_VALUE_DESERIALIZER
          value: org.egov.tracer.kafka.deserializer.ISTTimeZoneHashMapDeserializer
        - name: SPRING_KAFKA_PRODUCER_VALUE_SERIALIZER
          value: org.egov.tracer.kafka.serializer.ISTTimeZoneJsonSerializer
{% endif %}
        - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
          valueFrom:
            configMapKeyRef:
              name: egov-config
              key: kafka-brokers
        - name: APP_TIMEZONE
          valueFrom:
            configMapKeyRef:
              name: egov-config
              key: timezone
        - name: JAVA_OPTS
          value: "{{conf['lcms-workflow']['heap'] or '-Xmx64m -Xms64m'}}"
        - name: SERVER_PORT
          value: "8080"
        resources:
          requests:
            memory: "64Mi"
          limits:
            memory: "{{ conf['lcms-workflow']['memory_limits'] or "256Mi"}}"
