apiVersion: v1
kind: Service
metadata:
  name: lcms-services
  namespace: egov
  labels:
    app: lcms-services
    group: lcms
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: lcms-services
    group: lcms
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: lcms-services
  namespace: egov
spec:
  replicas: {{conf['lcms-services']['replicas']}}
  template:
    metadata:
      labels:
        app: lcms-services
        group: lcms
      annotations:
        pod.beta.kubernetes.io/init-containers: '[
          {
            "name": "lcms-services-db-migration",
            "image": "{{conf["lcms-services"]["db_migration_image"]}}",
            "env": [
              {"name": "DB_URL", "valueFrom": {"configMapKeyRef": {"name": "egov-config", "key": "db-url"}}},
              {"name": "SCHEMA_TABLE", "value": "lcms_services_schema"},
              {"name": "FLYWAY_USER", "valueFrom": {"secretKeyRef": {"name": "db", "key": "flyway-username"}}},
              {"name": "FLYWAY_PASSWORD", "valueFrom": {"secretKeyRef": {"name": "db", "key": "flyway-password"}}},
              {"name": "FLYWAY_LOCATIONS", "valueFrom": {"configMapKeyRef": {"name": "egov-config", "key": "flyway-locations"}}}
            ],
            "imagePullPolicy": "IfNotPresent"
          }
        ]'
    spec:
      containers:
      - name: lcms-services
        image: {{conf['lcms-services']['images'][0]}}
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_KAFKA_CONSUMER_KEY_DESERIALIZER
          value: org.apache.kafka.common.serialization.StringDeserializer
        - name: SPRING_KAFKA_CONSUMER_GROUP_ID
          value: lcms-create
        - name: SPRING_KAFKA_PRODUCER_KEY_SERIALIZER
          value: org.apache.kafka.common.serialization.StringSerializer
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            configMapKeyRef:
              name: egov-config
              key: db-url
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: db
              key: username
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db
              key: password
        - name: FLYWAY_ENABLED
          value: "false"
        - name: EGOV_SERVICES_TENANT_HOSTNAME
          value: "{{conf['egov-service-host']['tenant']}}"
        - name: EGOV_SERVICES_EGOV_IDGEN_HOSTNAME
          value: "{{conf['egov-service-host']['egov-idgen']}}"
{% if conf['egov-config']['serializers-timezone-in-ist'] %}
        - name: SPRING_KAFKA_CONSUMER_VALUE_DESERIALIZER
          value: org.egov.tracer.kafka.deserializer.ISTTimeZoneHashMapDeserializer
        - name: SPRING_KAFKA_PRODUCER_VALUE_SERIALIZER
          value: org.egov.tracer.kafka.serializer.ISTTimeZoneJsonSerializer
{% endif %}
        - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
          valueFrom:
            configMapKeyRef:
              name: egov-config
              key: kafka-brokers
        - name: APP_TIMEZONE
          valueFrom:
            configMapKeyRef:
              name: egov-config
              key: timezone
        - name: JAVA_OPTS
          value: "{{conf['lcms-services']['heap'] or '-Xmx64m -Xms64m'}}"
        - name: SERVER_PORT
          value: "8080"
        - name: EGOV_SERVICES_MDMS_SERVICES_HOSTNAME
          value: "{{conf['egov-service-host']['egov-mdms-service']}}"
        - name: EGOV_SERVICES_COMMON_MASTERS_HOSTNAME
          value: "{{conf['egov-service-host']['egov-common-masters']}}"
        resources:
          requests:
            memory: "64Mi"
          limits:
            memory: "{{conf['lcms-services']['memory_limits'] or "256Mi"}}"
