apiVersion: v1
kind: Service
metadata:
  name: lcms-notification
  namespace: egov
  labels:
    app: lcms-notification
    group: lcms
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: lcms-notification
    group: lcms
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: lcms-notification
  namespace: egov
spec:
  replicas: {{conf['lcms-notification']['replicas']}}
  template:
    metadata:
      labels:
        app: lcms-notification
        group: lcms
    spec:
      containers:
      - name: lcms-notification
        image: {{conf['lcms-notification']['images'][0]}}
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_KAFKA_CONSUMER_KEY_DESERIALIZER
          value: org.apache.kafka.common.serialization.StringDeserializer
        - name: SPRING_KAFKA_CONSUMER_GROUP_ID
          value: lcms-notification
        - name: SPRING_KAFKA_PRODUCER_KEY_SERIALIZER
          value: org.apache.kafka.common.serialization.StringSerializer
{% if conf['egov-config']['serializers-timezone-in-ist'] %}
        - name: SPRING_KAFKA_CONSUMER_VALUE_DESERIALIZER
          value: org.egov.tracer.kafka.deserializer.ISTTimeZoneHashMapDeserializer
        - name: SPRING_KAFKA_PRODUCER_VALUE_SERIALIZER
          value: org.egov.tracer.kafka.serializer.ISTTimeZoneJsonSerializer
{% endif %}
        - name: EGOV_SERVICES_EGOV_USER_HOSTNAME
          value: "{{conf['egov-service-host']['egov-user']}}"
        - name: EGOV_SERVICES_MDMS_SERVICES_HOSTNAME
          value: "{{conf['egov-service-host']['egov-mdms-service']}}"
        - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
          valueFrom:
            configMapKeyRef:
              name: egov-config
              key: kafka-brokers
        - name: APP_TIMEZONE
          valueFrom:
            configMapKeyRef:
              name: egov-config
              key: timezone
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            configMapKeyRef:
              name: egov-config
              key: db-url
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: db
              key: username
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db
              key: password
        - name: FLYWAY_ENABLED
          value: "false"
        - name: EGOV_SERVICES_EGOV_USER_HOSTNAME
          value: "{{conf['egov-service-host']['egov-user']}}"
        - name: JAVA_OPTS
          value: "{{conf['lcms-notification']['heap'] or '-Xmx64m -Xms64m'}}"
        - name: SERVER_PORT
          value: "8080"
        - name: EGOV_SERVICES_LCMS_SERVICES_HOSTNAME
          value: "{{conf['egov-service-host']['lcms-services']}}"
        resources:
          requests:
            memory: "64Mi"
          limits:
            memory: "{{conf['lcms-notification']['memory_limits'] or "256Mi"}}"
